import json
import re

# 1,000 Books from PDF 1 (Lifelong Library)
# Format: (id_num, title, author, year_str, level, category)

RAW_DATA = [
# 01. PSYCHOLOGICAL FICTION (45 books: 1-45)
(1, "The Idiot", "Fyodor Dostoevsky", "1869", "Foundation", "Psychological Fiction"),
(2, "Demons", "Fyodor Dostoevsky", "1872", "Foundation", "Psychological Fiction"),
(3, "Anna Karenina", "Leo Tolstoy", "1878", "Foundation", "Psychological Fiction"),
(4, "Madame Bovary", "Gustave Flaubert", "1857", "Foundation", "Psychological Fiction"),
(5, "The Red and the Black", "Stendhal", "1830", "Foundation", "Psychological Fiction"),
(6, "The Portrait of a Lady", "Henry James", "1881", "Foundation", "Psychological Fiction"),
(7, "The Turn of the Screw", "Henry James", "1898", "Foundation", "Psychological Fiction"),
(8, "The Awakening", "Kate Chopin", "1899", "Foundation", "Psychological Fiction"),
(9, "The Bell Jar", "Sylvia Plath", "1963", "Foundation", "Psychological Fiction"),
(10, "Mrs Dalloway", "Virginia Woolf", "1925", "Core", "Psychological Fiction"),
(11, "To the Lighthouse", "Virginia Woolf", "1927", "Core", "Psychological Fiction"),
(12, "The Waves", "Virginia Woolf", "1931", "Core", "Psychological Fiction"),
(13, "The Magic Mountain", "Thomas Mann", "1924", "Core", "Psychological Fiction"),
(14, "The Trial", "Franz Kafka", "1925", "Core", "Psychological Fiction"),
(15, "The Castle", "Franz Kafka", "1926", "Core", "Psychological Fiction"),
(16, "The Master and Margarita", "Mikhail Bulgakov", "1967", "Core", "Psychological Fiction"),
(17, "Blindness", "José Saramago", "1995", "Core", "Psychological Fiction"),
(18, "The Remains of the Day", "Kazuo Ishiguro", "1989", "Core", "Psychological Fiction"),
(19, "Never Let Me Go", "Kazuo Ishiguro", "2005", "Core", "Psychological Fiction"),
(20, "Atonement", "Ian McEwan", "2001", "Core", "Psychological Fiction"),
(21, "Disgrace", "J. M. Coetzee", "1999", "Intermediate", "Psychological Fiction"),
(22, "Beloved", "Toni Morrison", "1987", "Intermediate", "Psychological Fiction"),
(23, "Invisible Man", "Ralph Ellison", "1952", "Intermediate", "Psychological Fiction"),
(24, "Their Eyes Were Watching God", "Zora Neale Hurston", "1937", "Intermediate", "Psychological Fiction"),
(25, "The Great Gatsby", "F. Scott Fitzgerald", "1925", "Intermediate", "Psychological Fiction"),
(26, "The Sound and the Fury", "William Faulkner", "1929", "Intermediate", "Psychological Fiction"),
(27, "The Heart Is a Lonely Hunter", "Carson McCullers", "1940", "Intermediate", "Psychological Fiction"),
(28, "Stoner", "John Williams", "1965", "Intermediate", "Psychological Fiction"),
(29, "The Road", "Cormac McCarthy", "2006", "Intermediate", "Psychological Fiction"),
(30, "The Goldfinch", "Donna Tartt", "2013", "Intermediate", "Psychological Fiction"),
(31, "The Moviegoer", "Walker Percy", "1961", "Intermediate", "Psychological Fiction"),
(32, "The Hours", "Michael Cunningham", "1998", "Advanced", "Psychological Fiction"),
(33, "The Secret History", "Donna Tartt", "1992", "Advanced", "Psychological Fiction"),
(34, "The Good Soldier", "Ford Madox Ford", "1915", "Advanced", "Psychological Fiction"),
(35, "The Age of Innocence", "Edith Wharton", "1920", "Advanced", "Psychological Fiction"),
(36, "The House of Mirth", "Edith Wharton", "1905", "Advanced", "Psychological Fiction"),
(37, "Ethan Frome", "Edith Wharton", "1911", "Advanced", "Psychological Fiction"),
(38, "The Custom of the Country", "Edith Wharton", "1913", "Advanced", "Psychological Fiction"),
(39, "The Ambassadors", "Henry James", "1903", "Advanced", "Psychological Fiction"),
(40, "The Wings of the Dove", "Henry James", "1902", "Masterwork", "Psychological Fiction"),
(41, "The Sun Also Rises", "Ernest Hemingway", "1926", "Masterwork", "Psychological Fiction"),
(42, "For Whom the Bell Tolls", "Ernest Hemingway", "1940", "Masterwork", "Psychological Fiction"),
(43, "The Old Man and the Sea", "Ernest Hemingway", "1952", "Masterwork", "Psychological Fiction"),
(44, "The Catcher in the Rye", "J. D. Salinger", "1951", "Masterwork", "Psychological Fiction"),
(45, "The Talented Mr. Ripley", "Patricia Highsmith", "1955", "Masterwork", "Psychological Fiction"),

# 02. PRODUCTIVITY & TIME MANAGEMENT (25 books: 46-70)
(46, "Digital Minimalism", "Cal Newport", "2019", "Foundation", "Productivity & Time Management"),
(47, "Getting Things Done", "David Allen", "2001", "Foundation", "Productivity & Time Management"),
(48, "The Checklist Manifesto", "Atul Gawande", "2009", "Foundation", "Productivity & Time Management"),
(49, "Essentialism", "Greg McKeown", "2014", "Foundation", "Productivity & Time Management"),
(50, "Slow Productivity", "Cal Newport", "2024", "Foundation", "Productivity & Time Management"),
(51, "Make Time", "Jake Knapp & John Zeratsky", "2018", "Core", "Productivity & Time Management"),
(52, "168 Hours", "Laura Vanderkam", "2010", "Core", "Productivity & Time Management"),
(53, "The 80/20 Principle", "Richard Koch", "1997", "Core", "Productivity & Time Management"),
(54, "The Now Habit", "Neil Fiore", "1989", "Core", "Productivity & Time Management"),
(55, "The Procrastination Equation", "Piers Steel", "2010", "Core", "Productivity & Time Management"),
(56, "Rest", "Alex Soojung-Kim Pang", "2016", "Core", "Productivity & Time Management"),
(57, "Scarcity", "Sendhil Mullainathan & Eldar Shafir", "2013", "Intermediate", "Productivity & Time Management"),
(58, "Peak Performance", "Brad Stulberg & Steve Magness", "2017", "Intermediate", "Productivity & Time Management"),
(59, "The Power of Full Engagement", "Jim Loehr & Tony Schwartz", "2003", "Intermediate", "Productivity & Time Management"),
(60, "The One Thing", "Gary Keller & Jay Papasan", "2012", "Intermediate", "Productivity & Time Management"),
(61, "Atomic Habits", "James Clear", "2018", "Intermediate", "Productivity & Time Management"),
(62, "The Power of Habit", "Charles Duhigg", "2012", "Intermediate", "Productivity & Time Management"),
(63, "The Willpower Instinct", "Kelly McGonigal", "2011", "Advanced", "Productivity & Time Management"),
(64, "The Productivity Project", "Chris Bailey", "2016", "Advanced", "Productivity & Time Management"),
(65, "The 12 Week Year", "Brian Moran & Michael Lennington", "2013", "Advanced", "Productivity & Time Management"),
(66, "How to Do Nothing", "Jenny Odell", "2019", "Advanced", "Productivity & Time Management"),
(67, "Manage Your Day-to-Day", "99U", "2013", "Advanced", "Productivity & Time Management"),
(68, "Four Seconds", "Peter Bregman", "2015", "Masterwork", "Productivity & Time Management"),
(69, "The Power of Less", "Leo Babauta", "2009", "Masterwork", "Productivity & Time Management"),
(70, "The Productivity Ninja", "Graham Allcott", "2014", "Masterwork", "Productivity & Time Management"),

# 03. PSYCHOLOGY & HUMAN BEHAVIOUR (70 books: 71-140)
(71, "Predictably Irrational", "Dan Ariely", "2008", "Foundation", "Psychology & Human Behaviour"),
(72, "Influence", "Robert Cialdini", "1984", "Foundation", "Psychology & Human Behaviour"),
(73, "Pre-Suasion", "Robert Cialdini", "2016", "Foundation", "Psychology & Human Behaviour"),
(74, "The Social Animal", "Elliot Aronson", "1972", "Foundation", "Psychology & Human Behaviour"),
(75, "The Person and the Situation", "Lee Ross & Richard Nisbett", "1991", "Foundation", "Psychology & Human Behaviour"),
(76, "The Lucifer Effect", "Philip Zimbardo", "2007", "Foundation", "Psychology & Human Behaviour"),
(77, "Mistakes Were Made", "Carol Tavris & Elliot Aronson", "2007", "Foundation", "Psychology & Human Behaviour"),
(78, "The Happiness Hypothesis", "Jonathan Haidt", "2006", "Foundation", "Psychology & Human Behaviour"),
(79, "The Coddling of the American Mind", "Greg Lukianoff & Jonathan Haidt", "2018", "Foundation", "Psychology & Human Behaviour"),
(80, "The Elephant in the Brain", "Kevin Simler & Robin Hanson", "2018", "Foundation", "Psychology & Human Behaviour"),
(81, "Determined", "Robert Sapolsky", "2023", "Foundation", "Psychology & Human Behaviour"),
(82, "The Moral Animal", "Robert Wright", "1994", "Foundation", "Psychology & Human Behaviour"),
(83, "The Blank Slate", "Steven Pinker", "2002", "Foundation", "Psychology & Human Behaviour"),
(84, "How the Mind Works", "Steven Pinker", "1997", "Foundation", "Psychology & Human Behaviour"),
(85, "The Better Angels of Our Nature", "Steven Pinker", "2011", "Core", "Psychology & Human Behaviour"),
(86, "The Language Instinct", "Steven Pinker", "1994", "Core", "Psychology & Human Behaviour"),
(87, "The Denial of Death", "Ernest Becker", "1973", "Core", "Psychology & Human Behaviour"),
(88, "The Interpretation of Dreams", "Sigmund Freud", "1899", "Core", "Psychology & Human Behaviour"),
(89, "Civilization and Its Discontents", "Sigmund Freud", "1930", "Core", "Psychology & Human Behaviour"),
(90, "Man and His Symbols", "Carl Jung", "1964", "Core", "Psychology & Human Behaviour"),
(91, "Modern Man in Search of a Soul", "Carl Jung", "1933", "Core", "Psychology & Human Behaviour"),
(92, "Games People Play", "Eric Berne", "1964", "Core", "Psychology & Human Behaviour"),
(93, "Flow", "Mihaly Csikszentmihalyi", "1990", "Core", "Psychology & Human Behaviour"),
(94, "Drive", "Daniel Pink", "2009", "Core", "Psychology & Human Behaviour"),
(95, "Grit", "Angela Duckworth", "2016", "Core", "Psychology & Human Behaviour"),
(96, "Mindset", "Carol Dweck", "2006", "Core", "Psychology & Human Behaviour"),
(97, "The Marshmallow Test", "Walter Mischel", "2014", "Core", "Psychology & Human Behaviour"),
(98, "Stumbling on Happiness", "Daniel Gilbert", "2006", "Core", "Psychology & Human Behaviour"),
(99, "The Paradox of Choice", "Barry Schwartz", "2004", "Core", "Psychology & Human Behaviour"),
(100, "Connected", "Nicholas Christakis & James Fowler", "2009", "Core", "Psychology & Human Behaviour"),
(101, "Bowling Alone", "Robert Putnam", "2000", "Core", "Psychology & Human Behaviour"),
(102, "The Presentation of Self in Everyday Life", "Erving Goffman", "1956", "Intermediate", "Psychology & Human Behaviour"),
(103, "Asylums", "Erving Goffman", "1961", "Intermediate", "Psychology & Human Behaviour"),
(104, "The Crowd", "Gustave Le Bon", "1895", "Intermediate", "Psychology & Human Behaviour"),
(105, "The Gift", "Marcel Mauss", "1925", "Intermediate", "Psychology & Human Behaviour"),
(106, "The Body Keeps the Score", "Bessel van der Kolk", "2014", "Intermediate", "Psychology & Human Behaviour"),
(107, "The Paradox of Human Behavior", "Michael Gazzaniga", "2008", "Intermediate", "Psychology & Human Behaviour"),
(108, "The Happiness Trap", "Russ Harris", "2007", "Intermediate", "Psychology & Human Behaviour"),
(109, "The Social Leap", "William von Hippel", "2018", "Intermediate", "Psychology & Human Behaviour"),
(110, "The WEIRDest People in the World", "Joseph Henrich", "2020", "Intermediate", "Psychology & Human Behaviour"),
(111, "The Secret of Our Success", "Joseph Henrich", "2015", "Intermediate", "Psychology & Human Behaviour"),
(112, "The Cultural Animal", "Roy Baumeister", "2005", "Intermediate", "Psychology & Human Behaviour"),
(113, "The Nurture Assumption", "Judith Rich Harris", "1998", "Intermediate", "Psychology & Human Behaviour"),
(114, "The Origins of Virtue", "Matt Ridley", "1996", "Intermediate", "Psychology & Human Behaviour"),
(115, "The Blank Slate Debate", "Steven Pinker", "2002", "Intermediate", "Psychology & Human Behaviour"),
(116, "The Moral Tribes", "Joshua Greene", "2013", "Intermediate", "Psychology & Human Behaviour"),
(117, "The Geography of Thought", "Richard Nisbett", "2003", "Intermediate", "Psychology & Human Behaviour"),
(118, "The Paradox of Personality", "Mark Leary", "2019", "Intermediate", "Psychology & Human Behaviour"),
(119, "The Person You Mean to Be", "Dolly Chugh", "2018", "Intermediate", "Psychology & Human Behaviour"),
(120, "The Power of Context", "Malcolm Gladwell", "2000", "Advanced", "Psychology & Human Behaviour"),
(121, "Blink", "Malcolm Gladwell", "2005", "Advanced", "Psychology & Human Behaviour"),
(122, "Outliers", "Malcolm Gladwell", "2008", "Advanced", "Psychology & Human Behaviour"),
(123, "Talking to Strangers", "Malcolm Gladwell", "2019", "Advanced", "Psychology & Human Behaviour"),
(124, "The Tipping Point", "Malcolm Gladwell", "2000", "Advanced", "Psychology & Human Behaviour"),
(125, "The War for Kindness", "Jamil Zaki", "2019", "Advanced", "Psychology & Human Behaviour"),
(126, "The Science of Storytelling", "Will Storr", "2019", "Advanced", "Psychology & Human Behaviour"),
(127, "The Power of Strangers", "Joe Keohane", "2021", "Advanced", "Psychology & Human Behaviour"),
(128, "The Road Less Traveled", "M. Scott Peck", "1978", "Advanced", "Psychology & Human Behaviour"),
(129, "The Power of Moments", "Chip Heath & Dan Heath", "2017", "Advanced", "Psychology & Human Behaviour"),
(130, "The Upside of Irrationality", "Dan Ariely", "2010", "Advanced", "Psychology & Human Behaviour"),
(131, "The (Honest) Truth About Dishonesty", "Dan Ariely", "2012", "Advanced", "Psychology & Human Behaviour"),
(132, "The Chimp Paradox", "Steve Peters", "2012", "Masterwork", "Psychology & Human Behaviour"),
(133, "The Happiness Advantage", "Shawn Achor", "2010", "Masterwork", "Psychology & Human Behaviour"),
(134, "The Expectation Effect", "David Robson", "2022", "Masterwork", "Psychology & Human Behaviour"),
(135, "The Intelligence Trap", "David Robson", "2019", "Masterwork", "Psychology & Human Behaviour"),
(136, "The Laws of Human Nature", "Robert Greene", "2018", "Masterwork", "Psychology & Human Behaviour"),
(137, "The Invisible Gorilla", "Christopher Chabris & Daniel Simons", "2010", "Masterwork", "Psychology & Human Behaviour"),
(138, "The Man Who Lied to His Laptop", "Clifford Stoll", "2009", "Masterwork", "Psychology & Human Behaviour"),
(139, "The Mind Club", "Daniel Wegner & Kurt Gray", "2017", "Masterwork", "Psychology & Human Behaviour"),
(140, "The Psychology of Self-Deception", "Tony Stoltzfus", "2013", "Masterwork", "Psychology & Human Behaviour"),

# 04. EMOTIONAL INTELLIGENCE (30 books: 141-170)
(141, "Emotional Intelligence", "Daniel Goleman", "1995", "Foundation", "Emotional Intelligence"),
(142, "Primal Leadership", "Daniel Goleman, Richard Boyatzis & Annie McKee", "2002", "Foundation", "Emotional Intelligence"),
(143, "Social Intelligence", "Daniel Goleman", "2006", "Foundation", "Emotional Intelligence"),
(144, "Working with Emotional Intelligence", "Daniel Goleman", "1998", "Foundation", "Emotional Intelligence"),
(145, "Emotional Agility", "Susan David", "2016", "Foundation", "Emotional Intelligence"),
(146, "Permission to Feel", "Marc Brackett", "2019", "Foundation", "Emotional Intelligence"),
(147, "Atlas of the Heart", "Brené Brown", "2021", "Core", "Emotional Intelligence"),
(148, "Dare to Lead", "Brené Brown", "2018", "Core", "Emotional Intelligence"),
(149, "Rising Strong", "Brené Brown", "2015", "Core", "Emotional Intelligence"),
(150, "The Gifts of Imperfection", "Brené Brown", "2010", "Core", "Emotional Intelligence"),
(151, "Self-Compassion", "Kristin Neff", "2011", "Core", "Emotional Intelligence"),
(152, "Nonviolent Communication", "Marshall Rosenberg", "1999", "Core", "Emotional Intelligence"),
(153, "Get Out of Your Mind and Into Your Life", "Steven Hayes", "2005", "Core", "Emotional Intelligence"),
(154, "The Confidence Gap", "Russ Harris", "2010", "Intermediate", "Emotional Intelligence"),
(155, "Radical Acceptance", "Tara Brach", "2003", "Intermediate", "Emotional Intelligence"),
(156, "Why Has Nobody Told Me This Before?", "Julie Smith", "2022", "Intermediate", "Emotional Intelligence"),
(157, "Maybe You Should Talk to Someone", "Lori Gottlieb", "2019", "Intermediate", "Emotional Intelligence"),
(158, "The Emotional Life of Your Brain", "Richard Davidson & Sharon Begley", "2012", "Intermediate", "Emotional Intelligence"),
(159, "The Art of Happiness", "Dalai Lama & Howard Cutler", "1998", "Intermediate", "Emotional Intelligence"),
(160, "The Art of Loving", "Erich Fromm", "1956", "Intermediate", "Emotional Intelligence"),
(161, "The Mindful Self-Compassion Workbook", "Kristin Neff & Christopher Germer", "2018", "Intermediate", "Emotional Intelligence"),
(162, "The Untethered Soul", "Michael Singer", "2007", "Advanced", "Emotional Intelligence"),
(163, "Emotional Design", "Don Norman", "2004", "Advanced", "Emotional Intelligence"),
(164, "The Power of Vulnerability", "Brené Brown", "2013", "Advanced", "Emotional Intelligence"),
(165, "The Emotionally Intelligent Manager", "David Caruso & Peter Salovey", "2004", "Advanced", "Emotional Intelligence"),
(166, "The EQ Edge", "Steven Stein & Howard Book", "2000", "Advanced", "Emotional Intelligence"),
(167, "The Power of Showing Up", "Daniel Siegel & Tina Payne Bryson", "2020", "Masterwork", "Emotional Intelligence"),
(168, "The Whole-Brain Child", "Siegel & Bryson", "2011", "Masterwork", "Emotional Intelligence"),
(169, "The Art of Possibility", "Rosamund Stone Zander & Benjamin Zander", "2000", "Masterwork", "Emotional Intelligence"),
(170, "The Emotionally Intelligent Team", "Marcia Hughes & James Bradford Terrell", "2007", "Masterwork", "Emotional Intelligence"),

# 05. COMMUNICATION & SOCIAL SKILLS (40 books: 171-210)
(171, "How to Win Friends and Influence People", "Dale Carnegie", "1936", "Foundation", "Communication & Social Skills"),
(172, "Thanks for the Feedback", "Douglas Stone & Sheila Heen", "2014", "Foundation", "Communication & Social Skills"),
(173, "Just Listen", "Mark Goulston", "2009", "Foundation", "Communication & Social Skills"),
(174, "Supercommunicators", "Charles Duhigg", "2024", "Foundation", "Communication & Social Skills"),
(175, "You're Not Listening", "Kate Murphy", "2020", "Foundation", "Communication & Social Skills"),
(176, "Talk Like TED", "Carmine Gallo", "2014", "Foundation", "Communication & Social Skills"),
(177, "Resonate", "Nancy Duarte", "2010", "Foundation", "Communication & Social Skills"),
(178, "Presentation Zen", "Garr Reynolds", "2008", "Foundation", "Communication & Social Skills"),
(179, "Made to Stick", "Chip Heath & Dan Heath", "2007", "Core", "Communication & Social Skills"),
(180, "The Story Factor", "Annette Simmons", "2001", "Core", "Communication & Social Skills"),
(181, "Storytelling with Data", "Cole Nussbaumer Knaflic", "2015", "Core", "Communication & Social Skills"),
(182, "On Speaking Well", "Peggy Noonan", "1998", "Core", "Communication & Social Skills"),
(183, "Thank You for Arguing", "Jay Heinrichs", "2007", "Core", "Communication & Social Skills"),
(184, "The Art of Rhetoric", "Aristotle", "-350", "Core", "Communication & Social Skills"),
(185, "The Charisma Myth", "Olivia Fox Cabane", "2012", "Core", "Communication & Social Skills"),
(186, "Captivate", "Vanessa Van Edwards", "2017", "Core", "Communication & Social Skills"),
(187, "The Like Switch", "Jack Schafer & Marvin Karlins", "2015", "Core", "Communication & Social Skills"),
(188, "Friendship", "Lydia Denworth", "2020", "Core", "Communication & Social Skills"),
(189, "Platonic", "Marisa Franco", "2022", "Intermediate", "Communication & Social Skills"),
(190, "The Art of Gathering", "Priya Parker", "2018", "Intermediate", "Communication & Social Skills"),
(191, "Reclaiming Conversation", "Sherry Turkle", "2015", "Intermediate", "Communication & Social Skills"),
(192, "Quiet", "Susan Cain", "2012", "Intermediate", "Communication & Social Skills"),
(193, "Presence", "Amy Cuddy", "2015", "Intermediate", "Communication & Social Skills"),
(194, "The Culture Map", "Erin Meyer", "2014", "Intermediate", "Communication & Social Skills"),
(195, "The Art of Conversation", "Catherine Blyth", "2008", "Intermediate", "Communication & Social Skills"),
(196, "The Fine Art of Small Talk", "Debra Fine", "2005", "Intermediate", "Communication & Social Skills"),
(197, "How to Talk to Anyone", "Leil Lowndes", "1999", "Intermediate", "Communication & Social Skills"),
(198, "The Power of Talk", "Deborah Tannen", "1994", "Intermediate", "Communication & Social Skills"),
(199, "You Just Don't Understand", "Deborah Tannen", "1990", "Advanced", "Communication & Social Skills"),
(200, "Talking from 9 to 5", "Deborah Tannen", "1994", "Advanced", "Communication & Social Skills"),
(201, "The Mating Mind", "Geoffrey Miller", "2000", "Advanced", "Communication & Social Skills"),
(202, "The Presentation Secrets of Steve Jobs", "Carmine Gallo", "2009", "Advanced", "Communication & Social Skills"),
(203, "Talk", "Linda Rosenkrantz", "1968", "Advanced", "Communication & Social Skills"),
(204, "On Writing Well", "William Zinsser", "1976", "Advanced", "Communication & Social Skills"),
(205, "Writing Without Bullshit", "Josh Bernoff", "2016", "Advanced", "Communication & Social Skills"),
(206, "How to Be Right", "James O'Brien", "2018", "Masterwork", "Communication & Social Skills"),
(207, "The Art of Explanation", "Lee LeFever", "2012", "Masterwork", "Communication & Social Skills"),
(208, "The Sense of Style", "Steven Pinker", "2014", "Masterwork", "Communication & Social Skills"),
(209, "The Elements of Style", "Strunk & White", "1959", "Masterwork", "Communication & Social Skills"),
(210, "The Pyramid Principle", "Barbara Minto", "1987", "Masterwork", "Communication & Social Skills"),

# 06. PERSUASION & INFLUENCE (40 books: 211-250)
(211, "Yes!", "Noah Goldstein, Steve Martin & Robert Cialdini", "2008", "Foundation", "Persuasion & Influence"),
(212, "Propaganda", "Edward Bernays", "1928", "Foundation", "Persuasion & Influence"),
(213, "Crystallizing Public Opinion", "Edward Bernays", "1923", "Foundation", "Persuasion & Influence"),
(214, "Public Opinion", "Walter Lippmann", "1922", "Foundation", "Persuasion & Influence"),
(215, "The True Believer", "Eric Hoffer", "1951", "Foundation", "Persuasion & Influence"),
(216, "The 48 Laws of Power", "Robert Greene", "1998", "Foundation", "Persuasion & Influence"),
(217, "The Art of Seduction", "Robert Greene", "2001", "Foundation", "Persuasion & Influence"),
(218, "The 33 Strategies of War", "Robert Greene", "2006", "Foundation", "Persuasion & Influence"),
(219, "The Power of Persuasion", "Robert Levine", "2003", "Core", "Persuasion & Influence"),
(220, "The Art of Choosing", "Sheena Iyengar", "2010", "Core", "Persuasion & Influence"),
(221, "The Choice Factory", "Richard Shotton", "2018", "Core", "Persuasion & Influence"),
(222, "Contagious", "Jonah Berger", "2013", "Core", "Persuasion & Influence"),
(223, "To Sell Is Human", "Daniel Pink", "2012", "Core", "Persuasion & Influence"),
(224, "SPIN Selling", "Neil Rackham", "1988", "Core", "Persuasion & Influence"),
(225, "The Challenger Sale", "Matthew Dixon & Brent Adamson", "2011", "Core", "Persuasion & Influence"),
(226, "The 7 Habits of Highly Effective People", "Stephen Covey", "1989", "Core", "Persuasion & Influence"),
(227, "Subliminal", "Leonard Mlodinow", "2012", "Core", "Persuasion & Influence"),
(228, "The Power of Influence", "Zoe Chance", "2022", "Core", "Persuasion & Influence"),
(229, "The Catalyst", "Jonah Berger", "2020", "Intermediate", "Persuasion & Influence"),
(230, "The Art of Persuasion", "Bob Burg", "2011", "Intermediate", "Persuasion & Influence"),
(231, "Persuasion", "James Borg", "2007", "Intermediate", "Persuasion & Influence"),
(232, "How Minds Change", "David McRaney", "2022", "Intermediate", "Persuasion & Influence"),
(233, "Influence Is Your Superpower", "Zoe Chance", "2022", "Intermediate", "Persuasion & Influence"),
(234, "The Art of Influence", "Chris Widener", "2007", "Intermediate", "Persuasion & Influence"),
(235, "The Power of Others", "Michael Bond", "2014", "Intermediate", "Persuasion & Influence"),
(236, "The Crowd and the Public", "Gabriel Tarde", "1901", "Intermediate", "Persuasion & Influence"),
(237, "The Theory of Social Influence", "various", "2000", "Intermediate", "Persuasion & Influence"),
(238, "The Psychology of Persuasion", "Kevin Hogan", "1996", "Intermediate", "Persuasion & Influence"),
(239, "The Hidden Persuaders", "Vance Packard", "1957", "Advanced", "Persuasion & Influence"),
(240, "Age of Propaganda", "Pratkanis & Aronson", "1992", "Advanced", "Persuasion & Influence"),
(241, "The Psychology of Influence", "Robert Cialdini", "1980", "Advanced", "Persuasion & Influence"),
(242, "Influence: Science and Practice", "Robert Cialdini", "2001", "Advanced", "Persuasion & Influence"),
(243, "The Small BIG", "Goldstein, Martin & Cialdini", "2014", "Advanced", "Persuasion & Influence"),
(244, "The Influence of Persuasion", "Robert Cialdini", "2001", "Advanced", "Persuasion & Influence"),
(245, "The Psychology of Attitude Change", "Zimbardo & Leippe", "1991", "Advanced", "Persuasion & Influence"),
(246, "The Persuasion Handbook", "James Price Dillard & Michael Pfau", "2002", "Masterwork", "Persuasion & Influence"),
(247, "Influencer", "Patterson et al.", "2007", "Masterwork", "Persuasion & Influence"),
(248, "The Power of Noticing", "Max Bazerman", "2014", "Masterwork", "Persuasion & Influence"),
(249, "The Persuasion Code", "Christophe Morin et al.", "2018", "Masterwork", "Persuasion & Influence"),
(250, "The Dynamics of Persuasion", "Richard M. Perloff", "1993", "Masterwork", "Persuasion & Influence")
]

print(f"Loaded {len(RAW_DATA)} books in part 1")
