# 1,000 Books from PDF 1 (Lifelong Library)
# Categories 19 - 24 (Books 771 to 1000)

RAW_DATA = [
# 19. NEUROSCIENCE (35 books: 771-805)
(771, "The Brain That Changes Itself", "Norman Doidge", "2007", "Foundation", "Neuroscience"),
(772, "The Brain's Way of Healing", "Norman Doidge", "2015", "Foundation", "Neuroscience"),
(773, "The Man Who Mistook His Wife for a Hat", "Oliver Sacks", "1985", "Foundation", "Neuroscience"),
(774, "Awakenings", "Oliver Sacks", "1973", "Foundation", "Neuroscience"),
(775, "An Anthropologist on Mars", "Oliver Sacks", "1995", "Foundation", "Neuroscience"),
(776, "Musicophilia", "Oliver Sacks", "2007", "Foundation", "Neuroscience"),
(777, "Phantoms in the Brain", "V. S. Ramachandran", "1998", "Foundation", "Neuroscience"),
(778, "The Tell-Tale Brain", "V. S. Ramachandran", "2011", "Foundation", "Neuroscience"),
(779, "Incognito", "David Eagleman", "2011", "Foundation", "Neuroscience"),
(780, "The Brain", "David Eagleman", "2015", "Core", "Neuroscience"),
(781, "Livewired", "David Eagleman", "2020", "Core", "Neuroscience"),
(782, "Descartes' Error", "Antonio Damasio", "1994", "Core", "Neuroscience"),
(783, "The Feeling of What Happens", "Antonio Damasio", "1999", "Core", "Neuroscience"),
(784, "Looking for Spinoza", "Antonio Damasio", "2003", "Core", "Neuroscience"),
(785, "Self Comes to Mind", "Antonio Damasio", "2010", "Core", "Neuroscience"),
(786, "The Master and His Emissary", "Iain McGilchrist", "2009", "Core", "Neuroscience"),
(787, "The Matter With Things", "Iain McGilchrist", "2021", "Core", "Neuroscience"),
(788, "Behave", "Robert Sapolsky", "2017", "Intermediate", "Neuroscience"),
(789, "Why Zebras Don't Get Ulcers", "Robert Sapolsky", "1994", "Intermediate", "Neuroscience"),
(790, "The Trouble with Testosterone", "Robert Sapolsky", "1997", "Intermediate", "Neuroscience"),
(791, "A Primate's Memoir", "Robert Sapolsky", "2001", "Intermediate", "Neuroscience"),
(792, "The Tell-Tale Brain", "V. S. Ramachandran", "2011", "Intermediate", "Neuroscience"),
(793, "The Synaptic Self", "Joseph LeDoux", "2002", "Intermediate", "Neuroscience"),
(794, "The Emotional Brain", "Joseph LeDoux", "1996", "Intermediate", "Neuroscience"),
(795, "Anxious", "Joseph LeDoux", "2015", "Intermediate", "Neuroscience"),
(796, "The Deep History of Ourselves", "Joseph LeDoux", "2019", "Intermediate", "Neuroscience"),
(797, "How Emotions Are Made", "Lisa Feldman Barrett", "2017", "Advanced", "Neuroscience"),
(798, "Seven and a Half Lessons About the Brain", "Lisa Feldman Barrett", "2020", "Advanced", "Neuroscience"),
(799, "Other Minds", "Peter Godfrey-Smith", "2016", "Advanced", "Neuroscience"),
(800, "Metazoa", "Peter Godfrey-Smith", "2020", "Advanced", "Neuroscience"),
(801, "The Mind's I", "Douglas Hofstadter & Daniel Dennett", "1981", "Advanced", "Neuroscience"),
(802, "Consciousness Explained", "Daniel Dennett", "1991", "Masterwork", "Neuroscience"),
(803, "From Bacteria to Bach and Back", "Daniel Dennett", "2017", "Masterwork", "Neuroscience"),
(804, "The Idea of the Brain", "Matthew Cobb", "2020", "Masterwork", "Neuroscience"),
(805, "The Consciousness Instinct", "Michael Gazzaniga", "2018", "Masterwork", "Neuroscience"),

# 20. READING & THINKING (45 books: 806-850)
(806, "How to Read a Book", "Mortimer Adler & Charles Van Doren", "1940", "Foundation", "Reading & Thinking"),
(807, "The Great Conversation", "Robert Hutchins", "1952", "Foundation", "Reading & Thinking"),
(808, "The Well-Educated Mind", "Susan Wise Bauer", "2003", "Foundation", "Reading & Thinking"),
(809, "A History of Reading", "Alberto Manguel", "1996", "Foundation", "Reading & Thinking"),
(810, "The Library at Night", "Alberto Manguel", "2006", "Foundation", "Reading & Thinking"),
(811, "Proust and the Squid", "Maryanne Wolf", "2007", "Foundation", "Reading & Thinking"),
(812, "Reader, Come Home", "Maryanne Wolf", "2018", "Foundation", "Reading & Thinking"),
(813, "The Shallows", "Nicholas Carr", "2010", "Core", "Reading & Thinking"),
(814, "The Gutenberg Galaxy", "Marshall McLuhan", "1962", "Core", "Reading & Thinking"),
(815, "Understanding Media", "Marshall McLuhan", "1964", "Core", "Reading & Thinking"),
(816, "Amusing Ourselves to Death", "Neil Postman", "1985", "Core", "Reading & Thinking"),
(817, "Technopoly", "Neil Postman", "1992", "Core", "Reading & Thinking"),
(818, "The Closing of the American Mind", "Allan Bloom", "1987", "Core", "Reading & Thinking"),
(819, "The Western Canon", "Harold Bloom", "1994", "Core", "Reading & Thinking"),
(820, "How to Read and Why", "Harold Bloom", "2000", "Core", "Reading & Thinking"),
(821, "Shakespeare: The Invention of the Human", "Harold Bloom", "1998", "Core", "Reading & Thinking"),
(822, "An Experiment in Criticism", "C. S. Lewis", "1961", "Core", "Reading & Thinking"),
(823, "The Art of Reading", "Lin Yutang", "1937", "Intermediate", "Reading & Thinking"),
(824, "The Pleasures of Reading in an Age of Distraction", "Alan Jacobs", "2011", "Intermediate", "Reading & Thinking"),
(825, "How to Think", "Alan Jacobs", "2017", "Intermediate", "Reading & Thinking"),
(826, "The Art of Thinking Clearly", "Rolf Dobelli", "2011", "Intermediate", "Reading & Thinking"),
(827, "Superforecasting", "Philip Tetlock & Dan Gardner", "2015", "Intermediate", "Reading & Thinking"),
(828, "Expert Political Judgment", "Philip Tetlock", "2005", "Intermediate", "Reading & Thinking"),
(829, "The Scout Mindset", "Julia Galef", "2021", "Intermediate", "Reading & Thinking"),
(830, "Thinking in Bets", "Annie Duke", "2018", "Intermediate", "Reading & Thinking"),
(831, "The Signal and the Noise", "Nate Silver", "2012", "Intermediate", "Reading & Thinking"),
(832, "The Black Swan", "Nassim Nicholas Taleb", "2007", "Intermediate", "Reading & Thinking"),
(833, "Antifragile", "Nassim Nicholas Taleb", "2012", "Intermediate", "Reading & Thinking"),
(834, "Skin in the Game", "Nassim Nicholas Taleb", "2018", "Intermediate", "Reading & Thinking"),
(835, "The Bed of Procrustes", "Nassim Nicholas Taleb", "2010", "Advanced", "Reading & Thinking"),
(836, "The Model Thinker", "Scott Page", "2018", "Advanced", "Reading & Thinking"),
(837, "The Great Mental Models Volume 1", "Shane Parrish", "2019", "Advanced", "Reading & Thinking"),
(838, "The Great Mental Models Volume 2", "Shane Parrish", "2020", "Advanced", "Reading & Thinking"),
(839, "The Great Mental Models Volume 3", "Shane Parrish", "2021", "Advanced", "Reading & Thinking"),
(840, "Clear Thinking", "Shane Parrish", "2023", "Advanced", "Reading & Thinking"),
(841, "Poor Charlie's Almanack", "Peter Kaufman", "2005", "Advanced", "Reading & Thinking"),
(842, "Principles", "Ray Dalio", "2017", "Advanced", "Reading & Thinking"),
(843, "Thinking in Systems", "Donella Meadows", "2008", "Advanced", "Reading & Thinking"),
(844, "The Fifth Discipline", "Peter Senge", "1990", "Advanced", "Reading & Thinking"),
(845, "Gödel, Escher, Bach", "Douglas Hofstadter", "1979", "Masterwork", "Reading & Thinking"),
(846, "I Am a Strange Loop", "Douglas Hofstadter", "2007", "Masterwork", "Reading & Thinking"),
(847, "Metamagical Themas", "Douglas Hofstadter", "1985", "Masterwork", "Reading & Thinking"),
(848, "The Mind's I", "Douglas Hofstadter & Daniel Dennett", "1981", "Masterwork", "Reading & Thinking"),
(849, "Surfaces and Essences", "Hofstadter & Sander", "2013", "Masterwork", "Reading & Thinking"),
(850, "Fluid Concepts and Creative Analogies", "Douglas Hofstadter", "1995", "Masterwork", "Reading & Thinking"),

# 21. CREATIVITY (40 books: 851-890)
(851, "The Artist's Way", "Julia Cameron", "1992", "Foundation", "Creativity"),
(852, "The War of Art", "Steven Pressfield", "2002", "Foundation", "Creativity"),
(853, "Turning Pro", "Steven Pressfield", "2012", "Foundation", "Creativity"),
(854, "Do the Work", "Steven Pressfield", "2011", "Foundation", "Creativity"),
(855, "Big Magic", "Elizabeth Gilbert", "2015", "Foundation", "Creativity"),
(856, "Bird by Bird", "Anne Lamott", "1994", "Foundation", "Creativity"),
(857, "On Writing", "Stephen King", "2000", "Foundation", "Creativity"),
(858, "Steal Like an Artist", "Austin Kleon", "2012", "Foundation", "Creativity"),
(859, "Show Your Work!", "Austin Kleon", "2014", "Core", "Creativity"),
(860, "Keep Going", "Austin Kleon", "2019", "Core", "Creativity"),
(861, "Creativity, Inc.", "Ed Catmull", "2014", "Core", "Creativity"),
(862, "The Creative Act", "Rick Rubin", "2023", "Core", "Creativity"),
(863, "Creative Confidence", "Tom Kelley & David Kelley", "2013", "Core", "Creativity"),
(864, "The Art of Innovation", "Tom Kelley", "2001", "Core", "Creativity"),
(865, "Change by Design", "Tim Brown", "2009", "Core", "Creativity"),
(866, "The Design of Everyday Things", "Don Norman", "1988", "Core", "Creativity"),
(867, "The Act of Creation", "Arthur Koestler", "1964", "Core", "Creativity"),
(868, "Lateral Thinking", "Edward de Bono", "1970", "Intermediate", "Creativity"),
(869, "Six Thinking Hats", "Edward de Bono", "1985", "Intermediate", "Creativity"),
(870, "Po: Beyond Yes and No", "Edward de Bono", "1972", "Intermediate", "Creativity"),
(871, "The Mechanism of Mind", "Edward de Bono", "1969", "Intermediate", "Creativity"),
(872, "Where Good Ideas Come From", "Steven Johnson", "2010", "Intermediate", "Creativity"),
(873, "The Accidental Creative", "Todd Henry", "2011", "Intermediate", "Creativity"),
(874, "Daily Rituals", "Mason Currey", "2013", "Intermediate", "Creativity"),
(875, "The Creative Habit", "Twyla Tharp", "2003", "Intermediate", "Creativity"),
(876, "Keep It Moving", "Twyla Tharp", "2019", "Intermediate", "Creativity"),
(877, "The View from the Cheap Seats", "Neil Gaiman", "2016", "Intermediate", "Creativity"),
(878, "Art & Fear", "David Bayles & Ted Orland", "1993", "Advanced", "Creativity"),
(879, "Creative Selection", "Ken Kocienda", "2018", "Advanced", "Creativity"),
(880, "The Innovator's DNA", "Hal Gregersen", "2011", "Advanced", "Creativity"),
(881, "Originals", "Adam Grant", "2016", "Advanced", "Creativity"),
(882, "Wired to Create", "Scott Barry Kaufman & Carolyn Gregoire", "2015", "Advanced", "Creativity"),
(883, "Imagine: How Creativity Works", "Jonah Lehrer", "2012", "Advanced", "Creativity"),
(884, "Creativity", "Mihaly Csikszentmihalyi", "1996", "Advanced", "Creativity"),
(885, "The Element", "Ken Robinson", "2009", "Advanced", "Creativity"),
(886, "Finding Your Element", "Ken Robinson", "2013", "Masterwork", "Creativity"),
(887, "The Creative Priority", "Jerry Hirshberg", "1998", "Masterwork", "Creativity"),
(888, "A Whack on the Side of the Head", "Roger von Oech", "1983", "Masterwork", "Creativity"),
(889, "A Technique for Producing Ideas", "James Webb Young", "1940", "Masterwork", "Creativity"),
(890, "The Net and the Butterfly", "Olivia Fox Cabane & Judah Pollack", "2017", "Masterwork", "Creativity"),

# 22. CAREER & PROFESSIONAL DEVELOPMENT (35 books: 891-925)
(891, "So Good They Can't Ignore You", "Cal Newport", "2012", "Foundation", "Career & Professional Development"),
(892, "Deep Work", "Cal Newport", "2016", "Foundation", "Career & Professional Development"),
(893, "The Start-Up of You", "Reid Hoffman & Ben Casnocha", "2012", "Foundation", "Career & Professional Development"),
(894, "The Alliance", "Reid Hoffman, Ben Casnocha & Chris Yeh", "2014", "Foundation", "Career & Professional Development"),
(895, "Give and Take", "Adam Grant", "2013", "Foundation", "Career & Professional Development"),
(896, "Think Again", "Adam Grant", "2021", "Foundation", "Career & Professional Development"),
(897, "Hidden Potential", "Adam Grant", "2023", "Foundation", "Career & Professional Development"),
(898, "Range", "David Epstein", "2019", "Core", "Career & Professional Development"),
(899, "Designing Your Life", "Bill Burnett & Dave Evans", "2016", "Core", "Career & Professional Development"),
(900, "Designing Your Work Life", "Bill Burnett & Dave Evans", "2020", "Core", "Career & Professional Development"),
(901, "The Defining Decade", "Meg Jay", "2012", "Core", "Career & Professional Development"),
(902, "The Unspoken Rules", "Gorick Ng", "2021", "Core", "Career & Professional Development"),
(903, "What Color Is Your Parachute?", "Richard Bolles", "1970", "Core", "Career & Professional Development"),
(904, "Managing Oneself", "Peter Drucker", "1999", "Core", "Career & Professional Development"),
(905, "The Effective Executive", "Peter Drucker", "1967", "Core", "Career & Professional Development"),
(906, "Mastery", "Robert Greene", "2012", "Core", "Career & Professional Development"),
(907, "Peak", "Anders Ericsson & Robert Pool", "2016", "Intermediate", "Career & Professional Development"),
(908, "The First 90 Days", "Michael Watkins", "2003", "Intermediate", "Career & Professional Development"),
(909, "Your Next Five Moves", "Patrick Bet-David", "2020", "Intermediate", "Career & Professional Development"),
(910, "Playing Nice in Games That Aren't", "Barbara L. Vitale", "2005", "Intermediate", "Career & Professional Development"),
(911, "The Squiggly Career", "Helen Tupper & Sarah Ellis", "2020", "Intermediate", "Career & Professional Development"),
(912, "You Turn", "Ashley Stahl", "2021", "Intermediate", "Career & Professional Development"),
(913, "Pivot", "Jenny Blake", "2016", "Intermediate", "Career & Professional Development"),
(914, "Reinventing You", "Dorie Clark", "2013", "Intermediate", "Career & Professional Development"),
(915, "Stand Out", "Dorie Clark", "2015", "Advanced", "Career & Professional Development"),
(916, "The Long Game", "Dorie Clark", "2021", "Advanced", "Career & Professional Development"),
(917, "Never Eat Alone", "Keith Ferrazzi", "2005", "Advanced", "Career & Professional Development"),
(918, "Who's Got Your Back", "Keith Ferrazzi", "2009", "Advanced", "Career & Professional Development"),
(919, "Build", "Tony Fadell", "2022", "Advanced", "Career & Professional Development"),
(920, "Working", "Robert Caro", "2019", "Advanced", "Career & Professional Development"),
(921, "How to Be a Star at Work", "Robert Kelley", "1998", "Advanced", "Career & Professional Development"),
(922, "Career Warfare", "David D'Alessandro", "2003", "Masterwork", "Career & Professional Development"),
(923, "Executive Presence", "Sylvia Ann Hewlett", "2014", "Masterwork", "Career & Professional Development"),
(924, "The Dip", "Seth Godin", "2007", "Masterwork", "Career & Professional Development"),
(925, "Linchpin", "Seth Godin", "2010", "Masterwork", "Career & Professional Development"),

# 23. EDUCATION MANAGEMENT & POLICY (15 books: 926-940)
(926, "The Beautiful Tree", "James Tooley", "2009", "Foundation", "Education Management & Policy"),
(927, "The End of Average", "Todd Rose", "2016", "Foundation", "Education Management & Policy"),
(928, "Dumbing Us Down", "John Taylor Gatto", "1992", "Foundation", "Education Management & Policy"),
(929, "Weapons of Mass Instruction", "John Taylor Gatto", "2009", "Foundation", "Education Management & Policy"),
(930, "A Underground History of American Education", "John Taylor Gatto", "2001", "Core", "Education Management & Policy"),
(931, "The Knowledge Deficit", "E. D. Hirsch", "2006", "Core", "Education Management & Policy"),
(932, "Cultural Literacy", "E. D. Hirsch", "1987", "Core", "Education Management & Policy"),
(933, "Why Knowledge Matters", "E. D. Hirsch", "2016", "Core", "Education Management & Policy"),
(934, "The Schools We Need", "E. D. Hirsch", "1996", "Intermediate", "Education Management & Policy"),
(935, "In Defense of a Liberal Education", "Fareed Zakaria", "2015", "Intermediate", "Education Management & Policy"),
(936, "The Case Against Education", "Bryan Caplan", "2018", "Intermediate", "Education Management & Policy"),
(937, "Creative Schools", "Ken Robinson", "2015", "Advanced", "Education Management & Policy"),
(938, "Out of Our Minds", "Ken Robinson", "2001", "Advanced", "Education Management & Policy"),
(939, "Visible Learning", "John Hattie", "2008", "Masterwork", "Education Management & Policy"),
(940, "Teach Like a Champion", "Doug Lemov", "2010", "Masterwork", "Education Management & Policy"),

# 24. GREAT WORKS / MUST-READ CLASSICS (60 books: 941-1000)
(941, "The Epic of Gilgamesh", "Anonymous", "-2100", "Foundation", "Great Works / Must-Read Classics"),
(942, "The Iliad", "Homer", "-750", "Foundation", "Great Works / Must-Read Classics"),
(943, "The Odyssey", "Homer", "-725", "Foundation", "Great Works / Must-Read Classics"),
(944, "The Aeneid", "Virgil", "-19", "Foundation", "Great Works / Must-Read Classics"),
(945, "Metamorphoses", "Ovid", "8", "Foundation", "Great Works / Must-Read Classics"),
(946, "The Divine Comedy", "Dante Alighieri", "1320", "Foundation", "Great Works / Must-Read Classics"),
(947, "Inferno", "Dante Alighieri", "1320", "Foundation", "Great Works / Must-Read Classics"),
(948, "The Canterbury Tales", "Geoffrey Chaucer", "1400", "Foundation", "Great Works / Must-Read Classics"),
(949, "Don Quixote", "Miguel de Cervantes", "1605", "Foundation", "Great Works / Must-Read Classics"),
(950, "Paradise Lost", "John Milton", "1667", "Foundation", "Great Works / Must-Read Classics"),
(951, "Gulliver's Travels", "Jonathan Swift", "1726", "Foundation", "Great Works / Must-Read Classics"),
(952, "Candide", "Voltaire", "1759", "Foundation", "Great Works / Must-Read Classics"),
(953, "Faust", "Johann Wolfgang von Goethe", "1808", "Core", "Great Works / Must-Read Classics"),
(954, "The Sorrows of Young Werther", "Goethe", "1774", "Core", "Great Works / Must-Read Classics"),
(955, "Frankenstein", "Mary Shelley", "1818", "Core", "Great Works / Must-Read Classics"),
(956, "Pride and Prejudice", "Jane Austen", "1813", "Core", "Great Works / Must-Read Classics"),
(957, "Sense and Sensibility", "Jane Austen", "1811", "Core", "Great Works / Must-Read Classics"),
(958, "Emma", "Jane Austen", "1815", "Core", "Great Works / Must-Read Classics"),
(959, "Persuasion", "Jane Austen", "1817", "Core", "Great Works / Must-Read Classics"),
(960, "Jane Eyre", "Charlotte Brontë", "1847", "Core", "Great Works / Must-Read Classics"),
(961, "Wuthering Heights", "Emily Brontë", "1847", "Core", "Great Works / Must-Read Classics"),
(962, "Moby-Dick", "Herman Melville", "1851", "Core", "Great Works / Must-Read Classics"),
(963, "Bartleby, the Scrivener", "Herman Melville", "1853", "Core", "Great Works / Must-Read Classics"),
(964, "Great Expectations", "Charles Dickens", "1861", "Core", "Great Works / Must-Read Classics"),
(965, "A Tale of Two Cities", "Charles Dickens", "1859", "Core", "Great Works / Must-Read Classics"),
(966, "Bleak House", "Charles Dickens", "1853", "Core", "Great Works / Must-Read Classics"),
(967, "David Copperfield", "Charles Dickens", "1850", "Core", "Great Works / Must-Read Classics"),
(968, "Hard Times", "Charles Dickens", "1854", "Core", "Great Works / Must-Read Classics"),
(969, "Les Misérables", "Victor Hugo", "1862", "Core", "Great Works / Must-Read Classics"),
(970, "The Hunchback of Notre-Dame", "Victor Hugo", "1831", "Core", "Great Works / Must-Read Classics"),
(971, "War and Peace", "Leo Tolstoy", "1869", "Intermediate", "Great Works / Must-Read Classics"),
(972, "Middlemarch", "George Eliot", "1871", "Intermediate", "Great Works / Must-Read Classics"),
(973, "Silas Marner", "George Eliot", "1861", "Intermediate", "Great Works / Must-Read Classics"),
(974, "The Mill on the Floss", "George Eliot", "1860", "Intermediate", "Great Works / Must-Read Classics"),
(975, "The Picture of Dorian Gray", "Oscar Wilde", "1890", "Intermediate", "Great Works / Must-Read Classics"),
(976, "The Importance of Being Earnest", "Oscar Wilde", "1895", "Intermediate", "Great Works / Must-Read Classics"),
(977, "De Profundis", "Oscar Wilde", "1905", "Intermediate", "Great Works / Must-Read Classics"),
(978, "Heart of Darkness", "Joseph Conrad", "1899", "Intermediate", "Great Works / Must-Read Classics"),
(979, "Lord Jim", "Joseph Conrad", "1900", "Intermediate", "Great Works / Must-Read Classics"),
(980, "Nostromo", "Joseph Conrad", "1904", "Intermediate", "Great Works / Must-Read Classics"),
(981, "The Secret Agent", "Joseph Conrad", "1907", "Intermediate", "Great Works / Must-Read Classics"),
(982, "Ulysses", "James Joyce", "1922", "Advanced", "Great Works / Must-Read Classics"),
(983, "A Portrait of the Artist as a Young Man", "James Joyce", "1916", "Advanced", "Great Works / Must-Read Classics"),
(984, "Dubliners", "James Joyce", "1914", "Advanced", "Great Works / Must-Read Classics"),
(985, "Finnegans Wake", "James Joyce", "1939", "Advanced", "Great Works / Must-Read Classics"),
(986, "In Search of Lost Time", "Marcel Proust", "1913", "Advanced", "Great Works / Must-Read Classics"),
(987, "Swann's Way", "Marcel Proust", "1913", "Advanced", "Great Works / Must-Read Classics"),
(988, "One Hundred Years of Solitude", "Gabriel García Márquez", "1967", "Advanced", "Great Works / Must-Read Classics"),
(989, "Love in the Time of Cholera", "Gabriel García Márquez", "1985", "Advanced", "Great Works / Must-Read Classics"),
(990, "Ficciones", "Jorge Luis Borges", "1944", "Advanced", "Great Works / Must-Read Classics"),
(991, "The Aleph", "Jorge Luis Borges", "1949", "Advanced", "Great Works / Must-Read Classics"),
(992, "Labyrinths", "Jorge Luis Borges", "1962", "Masterwork", "Great Works / Must-Read Classics"),
(993, "Pale Fire", "Vladimir Nabokov", "1962", "Masterwork", "Great Works / Must-Read Classics"),
(994, "Lolita", "Vladimir Nabokov", "1955", "Masterwork", "Great Works / Must-Read Classics"),
(995, "Gravity's Rainbow", "Thomas Pynchon", "1973", "Masterwork", "Great Works / Must-Read Classics"),
(996, "The Crying of Lot 49", "Thomas Pynchon", "1966", "Masterwork", "Great Works / Must-Read Classics"),
(997, "Infinite Jest", "David Foster Wallace", "1996", "Masterwork", "Great Works / Must-Read Classics"),
(998, "Midnight's Children", "Salman Rushdie", "1981", "Masterwork", "Great Works / Must-Read Classics"),
(999, "Things Fall Apart", "Chinua Achebe", "1958", "Masterwork", "Great Works / Must-Read Classics"),
(1000, "Waiting for Godot", "Samuel Beckett", "1953", "Masterwork", "Great Works / Must-Read Classics")
]

print(f"Loaded {len(RAW_DATA)} books in part 4")
