# 1,000 Books from PDF 1 (Lifelong Library)
# Categories 13 - 18 (Books 521 to 770)

RAW_DATA = [
# 13. NEGOTIATION (25 books: 521-545)
(521, "Getting to Yes", "Roger Fisher, William Ury & Bruce Patton", "1981", "Foundation", "Negotiation"),
(522, "Getting Past No", "William Ury", "1991", "Foundation", "Negotiation"),
(523, "Never Split the Difference", "Chris Voss", "2016", "Foundation", "Negotiation"),
(524, "Beyond Reason", "Roger Fisher & Daniel Shapiro", "2005", "Foundation", "Negotiation"),
(525, "Difficult Conversations", "Stone, Patton & Heen", "1999", "Foundation", "Negotiation"),
(526, "Negotiating the Nonnegotiable", "Daniel Shapiro", "2016", "Core", "Negotiation"),
(527, "3-D Negotiation", "David Lax & James Sebenius", "2006", "Core", "Negotiation"),
(528, "Negotiation Genius", "Malhotra & Bazerman", "2007", "Core", "Negotiation"),
(529, "Bargaining for Advantage", "G. Richard Shell", "1999", "Core", "Negotiation"),
(530, "The Manager as Negotiator", "Lax & Sebenius", "1986", "Core", "Negotiation"),
(531, "The Art of Negotiation", "Michael Wheeler", "2013", "Core", "Negotiation"),
(532, "Negotiating at Work", "Deborah Kolb & Jessica Porter", "2009", "Intermediate", "Negotiation"),
(533, "The Mind and Heart of the Negotiator", "Leigh Thompson", "1998", "Intermediate", "Negotiation"),
(534, "Start with No", "Jim Camp", "2002", "Intermediate", "Negotiation"),
(535, "You Can Negotiate Anything", "Herb Cohen", "1980", "Intermediate", "Negotiation"),
(536, "Getting More", "Stuart Diamond", "2010", "Intermediate", "Negotiation"),
(537, "The Power of a Positive No", "William Ury", "2007", "Intermediate", "Negotiation"),
(538, "Good for You, Great for Me", "Lawrence Susskind", "2022", "Advanced", "Negotiation"),
(539, "Negotiating the Impossible", "Deepak Malhotra", "2016", "Advanced", "Negotiation"),
(540, "The Book of Real-World Negotiations", "Joshua Weiss", "2020", "Advanced", "Negotiation"),
(541, "Split the Pie", "Barry Nalebuff", "2022", "Advanced", "Negotiation"),
(542, "Negotiating Globally", "Jeanne Brett", "2007", "Advanced", "Negotiation"),
(543, "International Negotiation", "Jeswald Salacuse", "2003", "Masterwork", "Negotiation"),
(544, "Negotiation", "Brian Tracy", "2013", "Masterwork", "Negotiation"),
(545, "Negotiation Boot Camp", "Ed Brodow", "2006", "Masterwork", "Negotiation"),

# 14. FINANCE & INVESTING (50 books: 546-595)
(546, "The Little Book of Common Sense Investing", "John Bogle", "2007", "Foundation", "Finance & Investing"),
(547, "A Random Walk Down Wall Street", "Burton Malkiel", "1973", "Foundation", "Finance & Investing"),
(548, "Financial Intelligence", "Karen Berman & Joe Knight", "2006", "Foundation", "Finance & Investing"),
(549, "The Interpretation of Financial Statements", "Graham & Meredith", "1937", "Foundation", "Finance & Investing"),
(550, "The Intelligent Investor", "Benjamin Graham", "1949", "Foundation", "Finance & Investing"),
(551, "Security Analysis", "Benjamin Graham & David Dodd", "1934", "Foundation", "Finance & Investing"),
(552, "The Essays of Warren Buffett", "Lawrence Cunningham", "1997", "Foundation", "Finance & Investing"),
(553, "Common Stocks and Uncommon Profits", "Philip Fisher", "1958", "Foundation", "Finance & Investing"),
(554, "Investment Valuation", "Aswath Damodaran", "1995", "Foundation", "Finance & Investing"),
(555, "The Little Book of Valuation", "Aswath Damodaran", "2011", "Foundation", "Finance & Investing"),
(556, "Irrational Exuberance", "Robert Shiller", "2000", "Core", "Finance & Investing"),
(557, "The Intelligent Asset Allocator", "William Bernstein", "2000", "Core", "Finance & Investing"),
(558, "The Four Pillars of Investing", "William Bernstein", "2002", "Core", "Finance & Investing"),
(559, "The Bogleheads' Guide to Investing", "Larimore et al.", "2006", "Core", "Finance & Investing"),
(560, "Against the Gods", "Peter Bernstein", "1996", "Core", "Finance & Investing"),
(561, "Competition Demystified", "Bruce Greenwald & Judd Kahn", "2005", "Core", "Finance & Investing"),
(562, "One Up On Wall Street", "Peter Lynch", "1989", "Core", "Finance & Investing"),
(563, "Beating the Street", "Peter Lynch", "1993", "Core", "Finance & Investing"),
(564, "The Five Rules for Successful Stock Investing", "Pat Dorsey", "2004", "Core", "Finance & Investing"),
(565, "The Little Book That Still Beats the Market", "Joel Greenblatt", "2005", "Core", "Finance & Investing"),
(566, "You Can Be a Stock Market Genius", "Joel Greenblatt", "1997", "Core", "Finance & Investing"),
(567, "The Dhando Investor", "Mohnish Pabrai", "2007", "Core", "Finance & Investing"),
(568, "Margin of Safety", "Seth Klarman", "1991", "Intermediate", "Finance & Investing"),
(569, "The Warren Buffett Way", "Robert Hagstrom", "1994", "Intermediate", "Finance & Investing"),
(570, "Liar's Poker", "Michael Lewis", "1989", "Intermediate", "Finance & Investing"),
(571, "The Big Short", "Michael Lewis", "2010", "Intermediate", "Finance & Investing"),
(572, "When Genius Failed", "Roger Lowenstein", "2000", "Intermediate", "Finance & Investing"),
(573, "Too Big to Fail", "Andrew Ross Sorkin", "2009", "Intermediate", "Finance & Investing"),
(574, "This Time Is Different", "Reinhart & Rogoff", "2009", "Intermediate", "Finance & Investing"),
(575, "Manias, Panics, and Crashes", "Charles Kindleberger", "1978", "Intermediate", "Finance & Investing"),
(576, "The Alchemy of Finance", "George Soros", "1987", "Intermediate", "Finance & Investing"),
(577, "The Most Important Thing Illuminated", "Howard Marks", "2013", "Intermediate", "Finance & Investing"),
(578, "The Joys of Compounding", "Gautam Baid", "2018", "Intermediate", "Finance & Investing"),
(579, "Capital Returns", "Edward Chancellor", "2015", "Intermediate", "Finance & Investing"),
(580, "The Little Book That Beats the Market", "Joel Greenblatt", "2005", "Intermediate", "Finance & Investing"),
(581, "The Little Book of Behavioral Investing", "James Montier", "2007", "Advanced", "Finance & Investing"),
(582, "Value Investing", "Bruce Greenwald et al.", "2001", "Advanced", "Finance & Investing"),
(583, "Quality of Earnings", "O'Glove & Messier", "1990", "Advanced", "Finance & Investing"),
(584, "Financial Shenanigans", "Howard Schilit", "1993", "Advanced", "Finance & Investing"),
(585, "The Financial Numbers Game", "Charles Mulford & Eugene Comiskey", "2002", "Advanced", "Finance & Investing"),
(586, "Valuation", "McKinsey & Company", "1990", "Advanced", "Finance & Investing"),
(587, "Investment Science", "David Luenberger", "1997", "Advanced", "Finance & Investing"),
(588, "Expected Returns", "Antti Ilmanen", "2011", "Advanced", "Finance & Investing"),
(589, "Stocks for the Long Run", "Jeremy Siegel", "1994", "Advanced", "Finance & Investing"),
(590, "Triumph of the Optimists", "Dimson, Marsh & Staunton", "2002", "Masterwork", "Finance & Investing"),
(591, "The Future for Investors", "Jeremy Siegel", "2005", "Masterwork", "Finance & Investing"),
(592, "The Art of Execution", "Lee Freeman-Shor", "2015", "Masterwork", "Finance & Investing"),
(593, "The Warren Buffett Portfolio", "Robert Hagstrom", "1999", "Masterwork", "Finance & Investing"),
(594, "The Intelligent Investor's Workbook", "Benjamin Graham", "2008", "Masterwork", "Finance & Investing"),
(595, "The New Buffettology", "Mary Buffett & David Clark", "1997", "Masterwork", "Finance & Investing"),

# 15. ECONOMICS (50 books: 596-645)
(596, "The Undercover Economist", "Tim Harford", "2005", "Foundation", "Economics"),
(597, "Economics", "Samuelson & Nordhaus", "1948", "Foundation", "Economics"),
(598, "Basic Economics", "Thomas Sowell", "2000", "Foundation", "Economics"),
(599, "The Armchair Economist", "Steven Landsburg", "1993", "Foundation", "Economics"),
(600, "Principles of Economics", "N. Gregory Mankiw", "1998", "Foundation", "Economics"),
(601, "Microeconomic Analysis", "Hal Varian", "1992", "Foundation", "Economics"),
(602, "Macroeconomics", "N. Gregory Mankiw", "1992", "Foundation", "Economics"),
(603, "The Wealth of Nations", "Adam Smith", "1776", "Foundation", "Economics"),
(604, "The General Theory", "John Maynard Keynes", "1936", "Foundation", "Economics"),
(605, "Capitalism and Freedom", "Milton Friedman", "1962", "Foundation", "Economics"),
(606, "Free to Choose", "Milton & Rose Friedman", "1980", "Core", "Economics"),
(607, "Why Nations Fail", "Acemoglu & Robinson", "2012", "Core", "Economics"),
(608, "The Narrow Corridor", "Acemoglu & Robinson", "2019", "Core", "Economics"),
(609, "The Origins of Political Order", "Francis Fukuyama", "2011", "Core", "Economics"),
(610, "The End of History and the Last Man", "Francis Fukuyama", "1992", "Core", "Economics"),
(611, "Poor Economics", "Banerjee & Duflo", "2011", "Core", "Economics"),
(612, "Development Economics", "Debraj Ray", "1998", "Core", "Economics"),
(613, "The Bottom Billion", "Paul Collier", "2007", "Core", "Economics"),
(614, "The Elusive Quest for Growth", "William Easterly", "2001", "Core", "Economics"),
(615, "Capital in the Twenty-First Century", "Thomas Piketty", "2013", "Core", "Economics"),
(616, "The Great Leveler", "Walter Scheidel", "2017", "Core", "Economics"),
(617, "The Worldly Philosophers", "Robert Heilbroner", "1953", "Core", "Economics"),
(618, "The Great Transformation", "Karl Polanyi", "1944", "Intermediate", "Economics"),
(619, "Lords of Finance", "Liaquat Ahamed", "2009", "Intermediate", "Economics"),
(620, "The Road to Serfdom", "Friedrich Hayek", "1944", "Intermediate", "Economics"),
(621, "The Constitution of Liberty", "Friedrich Hayek", "1960", "Intermediate", "Economics"),
(622, "Human Action", "Ludwig von Mises", "1949", "Intermediate", "Economics"),
(623, "The Fatal Conceit", "Friedrich Hayek", "1988", "Intermediate", "Economics"),
(624, "Capitalism, Socialism and Democracy", "Joseph Schumpeter", "1942", "Intermediate", "Economics"),
(625, "The Theory of Economic Development", "Joseph Schumpeter", "1911", "Intermediate", "Economics"),
(626, "The Affluent Society", "John Kenneth Galbraith", "1958", "Intermediate", "Economics"),
(627, "The New Industrial State", "John Kenneth Galbraith", "1967", "Intermediate", "Economics"),
(628, "The Price of Inequality", "Joseph Stiglitz", "2012", "Intermediate", "Economics"),
(629, "The Great Escape", "Angus Deaton", "2013", "Intermediate", "Economics"),
(630, "Global Inequality", "Branko Milanovic", "2016", "Intermediate", "Economics"),
(631, "The Divide", "Jason Hickel", "2017", "Advanced", "Economics"),
(632, "The Ascent of Money", "Niall Ferguson", "2008", "Advanced", "Economics"),
(633, "The Box", "Marc Levinson", "2006", "Advanced", "Economics"),
(634, "Why the West Rules—For Now", "Ian Morris", "2010", "Advanced", "Economics"),
(635, "The Economics of Inequality", "Thomas Piketty", "2015", "Advanced", "Economics"),
(636, "The Undercover Economist Strikes Back", "Tim Harford", "2014", "Advanced", "Economics"),
(637, "The Courage to Act", "Ben Bernanke", "2015", "Advanced", "Economics"),
(638, "The Great Crash 1929", "John Kenneth Galbraith", "1955", "Advanced", "Economics"),
(639, "The General Theory of Employment", "Keynes", "1936", "Advanced", "Economics"),
(640, "The Use of Knowledge in Society", "Friedrich Hayek", "1945", "Masterwork", "Economics"),
(641, "The Economic Consequences of the Peace", "John Maynard Keynes", "1919", "Masterwork", "Economics"),
(642, "The Human Economy", "Karl Polanyi", "1977", "Masterwork", "Economics"),
(643, "The Mystery of Capital", "Hernando de Soto", "2000", "Masterwork", "Economics"),
(644, "The Wealth and Poverty of Nations", "David Landes", "1998", "Masterwork", "Economics"),
(645, "The Haves and the Have-Nots", "Branko Milanovic", "2011", "Masterwork", "Economics"),

# 16. WEALTH & MONEY PSYCHOLOGY (20 books: 646-665)
(646, "The Psychology of Money", "Morgan Housel", "2020", "Foundation", "Wealth & Money Psychology"),
(647, "Your Money or Your Life", "Vicki Robin & Joe Dominguez", "1992", "Foundation", "Wealth & Money Psychology"),
(648, "Die With Zero", "Bill Perkins", "2020", "Foundation", "Wealth & Money Psychology"),
(649, "The Millionaire Next Door", "Stanley & Danko", "1996", "Foundation", "Wealth & Money Psychology"),
(650, "The Simple Path to Wealth", "J. L. Collins", "2016", "Core", "Wealth & Money Psychology"),
(651, "The Status Game", "Will Storr", "2021", "Core", "Wealth & Money Psychology"),
(652, "The Theory of the Leisure Class", "Thorstein Veblen", "1899", "Core", "Wealth & Money Psychology"),
(653, "Misbehaving", "Richard Thaler", "2015", "Core", "Wealth & Money Psychology"),
(654, "Thinking, Fast and Slow", "Daniel Kahneman", "2011", "Core", "Wealth & Money Psychology"),
(655, "Nudge", "Thaler & Sunstein", "2008", "Intermediate", "Wealth & Money Psychology"),
(656, "The Most Important Thing", "Howard Marks", "2011", "Intermediate", "Wealth & Money Psychology"),
(657, "Fooled by Randomness", "Nassim Taleb", "2001", "Intermediate", "Wealth & Money Psychology"),
(658, "The Almanack of Naval Ravikant", "Eric Jorgenson", "2020", "Intermediate", "Wealth & Money Psychology"),
(659, "The Theory of Moral Sentiments", "Adam Smith", "1759", "Intermediate", "Wealth & Money Psychology"),
(660, "Nicomachean Ethics", "Aristotle", "-340", "Advanced", "Wealth & Money Psychology"),
(661, "The Consolation of Philosophy", "Boethius", "524", "Advanced", "Wealth & Money Psychology"),
(662, "The Antidote", "Oliver Burkeman", "2012", "Advanced", "Wealth & Money Psychology"),
(663, "The Good Life", "Waldinger & Schulz", "2023", "Masterwork", "Wealth & Money Psychology"),
(664, "The Art of Money", "Bari Tessler", "2016", "Masterwork", "Wealth & Money Psychology"),
(665, "The Soul of Money", "Lynne Twist", "2017", "Masterwork", "Wealth & Money Psychology"),

# 17. BIOGRAPHIES & AUTOBIOGRAPHIES (50 books: 666-715)
(666, "Leonardo da Vinci", "Walter Isaacson", "2017", "Foundation", "Biographies & Autobiographies"),
(667, "Einstein: His Life and Universe", "Walter Isaacson", "2007", "Foundation", "Biographies & Autobiographies"),
(668, "Steve Jobs", "Walter Isaacson", "2011", "Foundation", "Biographies & Autobiographies"),
(669, "Benjamin Franklin", "Walter Isaacson", "2003", "Foundation", "Biographies & Autobiographies"),
(670, "The Innovators", "Walter Isaacson", "2014", "Foundation", "Biographies & Autobiographies"),
(671, "The Man Who Knew Infinity", "Robert Kanigel", "1991", "Foundation", "Biographies & Autobiographies"),
(672, "Surely You're Joking, Mr. Feynman!", "Richard Feynman", "1985", "Foundation", "Biographies & Autobiographies"),
(673, "What Do You Care What Other People Think?", "Richard Feynman", "1988", "Foundation", "Biographies & Autobiographies"),
(674, "The Double Helix", "James Watson", "1968", "Foundation", "Biographies & Autobiographies"),
(675, "Titan", "Ron Chernow", "1998", "Foundation", "Biographies & Autobiographies"),
(676, "The House of Morgan", "Ron Chernow", "1990", "Core", "Biographies & Autobiographies"),
(677, "Alexander Hamilton", "Ron Chernow", "2004", "Core", "Biographies & Autobiographies"),
(678, "Washington: A Life", "Ron Chernow", "2010", "Core", "Biographies & Autobiographies"),
(679, "Grant", "Ron Chernow", "2017", "Core", "Biographies & Autobiographies"),
(680, "Team of Rivals", "Doris Kearns Goodwin", "2005", "Core", "Biographies & Autobiographies"),
(681, "The Power Broker", "Robert Caro", "1974", "Core", "Biographies & Autobiographies"),
(682, "Master of the Senate", "Robert Caro", "2002", "Core", "Biographies & Autobiographies"),
(683, "Churchill: Walking with Destiny", "Andrew Roberts", "2018", "Core", "Biographies & Autobiographies"),
(684, "Long Walk to Freedom", "Nelson Mandela", "1994", "Core", "Biographies & Autobiographies"),
(685, "The Autobiography of Malcolm X", "Malcolm X & Alex Haley", "1965", "Core", "Biographies & Autobiographies"),
(686, "The Education of Henry Adams", "Henry Adams", "1907", "Core", "Biographies & Autobiographies"),
(687, "The Autobiography of Benjamin Franklin", "Benjamin Franklin", "1791", "Core", "Biographies & Autobiographies"),
(688, "Narrative of the Life of Frederick Douglass", "Frederick Douglass", "1845", "Intermediate", "Biographies & Autobiographies"),
(689, "The Story of My Life", "Helen Keller", "1903", "Intermediate", "Biographies & Autobiographies"),
(690, "The Diary of a Young Girl", "Anne Frank", "1947", "Intermediate", "Biographies & Autobiographies"),
(691, "Night", "Elie Wiesel", "1956", "Intermediate", "Biographies & Autobiographies"),
(692, "Open", "Andre Agassi", "2009", "Intermediate", "Biographies & Autobiographies"),
(693, "Greenlights", "Matthew McConaughey", "2020", "Intermediate", "Biographies & Autobiographies"),
(694, "Speak, Memory", "Vladimir Nabokov", "1951", "Intermediate", "Biographies & Autobiographies"),
(695, "Just Kids", "Patti Smith", "2010", "Intermediate", "Biographies & Autobiographies"),
(696, "Born to Run", "Bruce Springsteen", "2016", "Intermediate", "Biographies & Autobiographies"),
(697, "Educated", "Tara Westover", "2018", "Intermediate", "Biographies & Autobiographies"),
(698, "Becoming", "Michelle Obama", "2018", "Intermediate", "Biographies & Autobiographies"),
(699, "Dreams from My Father", "Barack Obama", "1995", "Intermediate", "Biographies & Autobiographies"),
(700, "The Story of My Experiments with Truth", "Mahatma Gandhi", "1927", "Intermediate", "Biographies & Autobiographies"),
(701, "The Autobiography of a Yogi", "Paramahansa Yogananda", "1946", "Advanced", "Biographies & Autobiographies"),
(702, "Seven Pillars of Wisdom", "T. E. Lawrence", "1926", "Advanced", "Biographies & Autobiographies"),
(703, "Personal History", "Katharine Graham", "1997", "Advanced", "Biographies & Autobiographies"),
(704, "The Years of Lyndon Johnson", "Robert Caro", "1982", "Advanced", "Biographies & Autobiographies"),
(705, "My Life", "Isadora Duncan", "1927", "Advanced", "Biographies & Autobiographies"),
(706, "Memoirs of Hadrian", "Marguerite Yourcenar", "1951", "Advanced", "Biographies & Autobiographies"),
(707, "Napoleon: A Life", "Andrew Roberts", "2014", "Advanced", "Biographies & Autobiographies"),
(708, "Alexander the Great", "Robin Lane Fox", "1973", "Advanced", "Biographies & Autobiographies"),
(709, "Cleopatra", "Stacy Schiff", "2010", "Advanced", "Biographies & Autobiographies"),
(710, "Catherine the Great", "Robert K. Massie", "2011", "Masterwork", "Biographies & Autobiographies"),
(711, "Peter the Great", "Robert K. Massie", "1980", "Masterwork", "Biographies & Autobiographies"),
(712, "Churchill", "Roy Jenkins", "2001", "Masterwork", "Biographies & Autobiographies"),
(713, "The Last Lion", "Manchester & Reid", "1983", "Masterwork", "Biographies & Autobiographies"),
(714, "Lyndon Johnson and the American Dream", "Doris Kearns Goodwin", "1976", "Masterwork", "Biographies & Autobiographies"),
(715, "Truman", "David McCullough", "1992", "Masterwork", "Biographies & Autobiographies"),

# 18. HISTORY (55 books: 716-770)
(716, "A Little History of the World", "E. H. Gombrich", "1935", "Foundation", "History"),
(717, "Sapiens", "Yuval Noah Harari", "2011", "Foundation", "History"),
(718, "The Lessons of History", "Will & Ariel Durant", "1968", "Foundation", "History"),
(719, "The Dawn of Everything", "Graeber & Wengrow", "2021", "Foundation", "History"),
(720, "The Silk Roads", "Peter Frankopan", "2015", "Foundation", "History"),
(721, "The Inheritance of Rome", "Chris Wickham", "2009", "Foundation", "History"),
(722, "The Histories", "Herodotus", "-440", "Foundation", "History"),
(723, "History of the Peloponnesian War", "Thucydides", "-400", "Foundation", "History"),
(724, "The Decline and Fall of the Roman Empire", "Edward Gibbon", "1776", "Foundation", "History"),
(725, "The Muqaddimah", "Ibn Khaldun", "1377", "Foundation", "History"),
(726, "The Discovery of India", "Jawaharlal Nehru", "1946", "Foundation", "History"),
(727, "India After Gandhi", "Ramachandra Guha", "2007", "Core", "History"),
(728, "Early India", "Romila Thapar", "2002", "Core", "History"),
(729, "The Wonder That Was India", "A. L. Basham", "1954", "Core", "History"),
(730, "Plassey to Partition", "Sekhar Bandyopadhyay", "2004", "Core", "History"),
(731, "Mughal India", "John F. Richards", "1993", "Core", "History"),
(732, "Anarchy", "William Dalrymple", "2019", "Core", "History"),
(733, "The Last Mughal", "William Dalrymple", "2006", "Core", "History"),
(734, "The Argumentative Indian", "Amartya Sen", "2005", "Core", "History"),
(735, "Genghis Khan and the Making of the Modern World", "Jack Weatherford", "2004", "Core", "History"),
(736, "The Great Divergence", "Kenneth Pomeranz", "2000", "Core", "History"),
(737, "The French Revolution", "Christopher Hibbert", "1980", "Core", "History"),
(738, "Citizens", "Simon Schama", "1989", "Core", "History"),
(739, "The Sleepwalkers", "Christopher Clark", "2012", "Core", "History"),
(740, "The Second World War", "Antony Beevor", "2012", "Intermediate", "History"),
(741, "Bloodlands", "Timothy Snyder", "2010", "Intermediate", "History"),
(742, "Postwar", "Tony Judt", "2005", "Intermediate", "History"),
(743, "The Cold War", "John Lewis Gaddis", "2005", "Intermediate", "History"),
(744, "The Global Cold War", "Odd Arne Westad", "2005", "Intermediate", "History"),
(745, "Orientalism", "Edward Said", "1978", "Intermediate", "History"),
(746, "The Wretched of the Earth", "Frantz Fanon", "1961", "Intermediate", "History"),
(747, "The Age of Empire", "Eric Hobsbawm", "1987", "Intermediate", "History"),
(748, "The Age of Extremes", "Eric Hobsbawm", "1994", "Intermediate", "History"),
(749, "Empire", "Niall Ferguson", "2003", "Intermediate", "History"),
(750, "The Communist Manifesto", "Marx & Engels", "1848", "Intermediate", "History"),
(751, "The Gulag Archipelago", "Aleksandr Solzhenitsyn", "1973", "Intermediate", "History"),
(752, "The Making of the Atomic Bomb", "Richard Rhodes", "1986", "Intermediate", "History"),
(753, "The Warmth of Other Suns", "Isabel Wilkerson", "2010", "Intermediate", "History"),
(754, "The Crusades", "Thomas Asbridge", "2010", "Advanced", "History"),
(755, "The Ottoman Empire", "Caroline Finkel", "2005", "Advanced", "History"),
(756, "The Plantagenets", "Dan Jones", "2012", "Advanced", "History"),
(757, "The Norman Conquest", "Marc Morris", "2012", "Advanced", "History"),
(758, "SPQR", "Mary Beard", "2015", "Advanced", "History"),
(759, "The Fate of Rome", "Kyle Harper", "2017", "Advanced", "History"),
(760, "The Great Sea", "David Abulafia", "2011", "Advanced", "History"),
(761, "The Age of Revolution", "Eric Hobsbawm", "1962", "Advanced", "History"),
(762, "The Age of Capital", "Eric Hobsbawm", "1975", "Advanced", "History"),
(763, "The Global Transformation", "Jürgen Osterhammel", "2014", "Advanced", "History"),
(764, "The Pursuit of Power", "Richard J. Evans", "2016", "Masterwork", "History"),
(765, "The Cold War: A New History", "John Lewis Gaddis", "2005", "Masterwork", "History"),
(766, "The Habsburgs", "Martyn Rady", "2020", "Masterwork", "History"),
(767, "The Roman Revolution", "Ronald Syme", "1939", "Masterwork", "History"),
(768, "Rubicon", "Tom Holland", "2003", "Masterwork", "History"),
(769, "Persian Fire", "Tom Holland", "2005", "Masterwork", "History"),
(770, "Dominion", "Tom Holland", "2019", "Masterwork", "History")
]

print(f"Loaded {len(RAW_DATA)} books in part 3")
