# 1,000 Books from PDF 1 (Lifelong Library)
# Categories 07 - 12 (Books 251 to 520)

RAW_DATA = [
# 07. PHILOSOPHY (65 books: 251-315)
(251, "What Does It All Mean?", "Thomas Nagel", "1987", "Foundation", "Philosophy"),
(252, "The Problems of Philosophy", "Bertrand Russell", "1912", "Foundation", "Philosophy"),
(253, "A History of Western Philosophy", "Bertrand Russell", "1945", "Foundation", "Philosophy"),
(254, "The Story of Philosophy", "Will Durant", "1926", "Foundation", "Philosophy"),
(255, "Sophie's World", "Jostein Gaarder", "1991", "Foundation", "Philosophy"),
(256, "Apology", "Plato", "-399", "Foundation", "Philosophy"),
(257, "Crito", "Plato", "-399", "Foundation", "Philosophy"),
(258, "Meno", "Plato", "-385", "Foundation", "Philosophy"),
(259, "Republic", "Plato", "-380", "Foundation", "Philosophy"),
(260, "Symposium", "Plato", "-385", "Foundation", "Philosophy"),
(261, "Phaedo", "Plato", "-380", "Foundation", "Philosophy"),
(262, "Politics", "Aristotle", "-350", "Foundation", "Philosophy"),
(263, "Metaphysics", "Aristotle", "-350", "Foundation", "Philosophy"),
(264, "On the Soul", "Aristotle", "-350", "Core", "Philosophy"),
(265, "Meditations", "Marcus Aurelius", "180", "Core", "Philosophy"),
(266, "Enchiridion", "Epictetus", "125", "Core", "Philosophy"),
(267, "Letters from a Stoic", "Seneca", "65", "Core", "Philosophy"),
(268, "On the Shortness of Life", "Seneca", "49", "Core", "Philosophy"),
(269, "Confessions", "Augustine", "397", "Core", "Philosophy"),
(270, "Meditations on First Philosophy", "René Descartes", "1641", "Core", "Philosophy"),
(271, "Leviathan", "Thomas Hobbes", "1651", "Core", "Philosophy"),
(272, "An Essay Concerning Human Understanding", "John Locke", "1689", "Core", "Philosophy"),
(273, "Treatise of Human Nature", "David Hume", "1739", "Core", "Philosophy"),
(274, "An Enquiry Concerning Human Understanding", "David Hume", "1748", "Core", "Philosophy"),
(275, "The Social Contract", "Jean-Jacques Rousseau", "1762", "Core", "Philosophy"),
(276, "Critique of Pure Reason", "Immanuel Kant", "1781", "Core", "Philosophy"),
(277, "Groundwork of the Metaphysics of Morals", "Immanuel Kant", "1785", "Core", "Philosophy"),
(278, "Critique of Practical Reason", "Immanuel Kant", "1788", "Core", "Philosophy"),
(279, "Phenomenology of Spirit", "G. W. F. Hegel", "1807", "Core", "Philosophy"),
(280, "On Liberty", "John Stuart Mill", "1859", "Intermediate", "Philosophy"),
(281, "Utilitarianism", "John Stuart Mill", "1863", "Intermediate", "Philosophy"),
(282, "On the Genealogy of Morality", "Friedrich Nietzsche", "1887", "Intermediate", "Philosophy"),
(283, "Beyond Good and Evil", "Friedrich Nietzsche", "1886", "Intermediate", "Philosophy"),
(284, "Thus Spoke Zarathustra", "Friedrich Nietzsche", "1883", "Intermediate", "Philosophy"),
(285, "The Gay Science", "Friedrich Nietzsche", "1882", "Intermediate", "Philosophy"),
(286, "The World as Will and Representation", "Arthur Schopenhauer", "1818", "Intermediate", "Philosophy"),
(287, "The Human Condition", "Hannah Arendt", "1958", "Intermediate", "Philosophy"),
(288, "The Origins of Totalitarianism", "Hannah Arendt", "1951", "Intermediate", "Philosophy"),
(289, "A Theory of Justice", "John Rawls", "1971", "Intermediate", "Philosophy"),
(290, "Anarchy, State, and Utopia", "Robert Nozick", "1974", "Intermediate", "Philosophy"),
(291, "The Open Society and Its Enemies", "Karl Popper", "1945", "Intermediate", "Philosophy"),
(292, "Ethics: Inventing Right and Wrong", "J. L. Mackie", "1977", "Intermediate", "Philosophy"),
(293, "The View from Nowhere", "Thomas Nagel", "1986", "Intermediate", "Philosophy"),
(294, "The Sources of Normativity", "Christine Korsgaard", "1996", "Intermediate", "Philosophy"),
(295, "After Virtue", "Alasdair MacIntyre", "1981", "Intermediate", "Philosophy"),
(296, "Justice", "Michael Sandel", "2009", "Advanced", "Philosophy"),
(297, "The Idea of Justice", "Amartya Sen", "2009", "Advanced", "Philosophy"),
(298, "The Examined Life", "Stephen Grosz", "2013", "Advanced", "Philosophy"),
(299, "The Pig That Wants to Be Eaten", "Julian Baggini", "2005", "Advanced", "Philosophy"),
(300, "The Fundamentals of Ethics", "Russ Shafer-Landau", "2003", "Advanced", "Philosophy"),
(301, "The Nicomachean Ethics", "Aristotle", "-340", "Advanced", "Philosophy"),
(302, "Rhetoric", "Aristotle", "-350", "Advanced", "Philosophy"),
(303, "Poetics", "Aristotle", "-335", "Advanced", "Philosophy"),
(304, "The Tao Te Ching", "Laozi", "-500", "Advanced", "Philosophy"),
(305, "The Analects", "Confucius", "-475", "Advanced", "Philosophy"),
(306, "The Bhagavad Gita", "Vyasa, traditional", "-200", "Advanced", "Philosophy"),
(307, "The Enneads", "Plotinus", "250", "Advanced", "Philosophy"),
(308, "Summa Theologiae", "Thomas Aquinas", "1265", "Masterwork", "Philosophy"),
(309, "The Guide for the Perplexed", "Maimonides", "1190", "Masterwork", "Philosophy"),
(310, "The City of God", "Augustine", "426", "Masterwork", "Philosophy"),
(311, "The Praise of Folly", "Erasmus", "1511", "Masterwork", "Philosophy"),
(312, "The Advancement of Learning", "Francis Bacon", "1605", "Masterwork", "Philosophy"),
(313, "Novum Organum", "Francis Bacon", "1620", "Masterwork", "Philosophy"),
(314, "Discourse on Method", "René Descartes", "1637", "Masterwork", "Philosophy"),
(315, "Ethics", "Baruch Spinoza", "1677", "Masterwork", "Philosophy"),

# 08. EXISTENTIALISM (25 books: 316-340)
(316, "Notes from Underground", "Fyodor Dostoevsky", "1864", "Foundation", "Existentialism"),
(317, "The Death of Ivan Ilyich", "Leo Tolstoy", "1886", "Foundation", "Existentialism"),
(318, "The Metamorphosis", "Franz Kafka", "1915", "Foundation", "Existentialism"),
(319, "The Stranger", "Albert Camus", "1942", "Foundation", "Existentialism"),
(320, "The Myth of Sisyphus", "Albert Camus", "1942", "Foundation", "Existentialism"),
(321, "The Plague", "Albert Camus", "1947", "Core", "Existentialism"),
(322, "The Fall", "Albert Camus", "1956", "Core", "Existentialism"),
(323, "Existentialism Is a Humanism", "Jean-Paul Sartre", "1946", "Core", "Existentialism"),
(324, "Being and Nothingness", "Jean-Paul Sartre", "1943", "Core", "Existentialism"),
(325, "Nausea", "Jean-Paul Sartre", "1938", "Core", "Existentialism"),
(326, "No Exit", "Jean-Paul Sartre", "1944", "Core", "Existentialism"),
(327, "Fear and Trembling", "Søren Kierkegaard", "1843", "Intermediate", "Existentialism"),
(328, "The Concept of Anxiety", "Søren Kierkegaard", "1844", "Intermediate", "Existentialism"),
(329, "Either/Or", "Søren Kierkegaard", "1843", "Intermediate", "Existentialism"),
(330, "The Sickness Unto Death", "Søren Kierkegaard", "1849", "Intermediate", "Existentialism"),
(331, "The Ethics of Ambiguity", "Simone de Beauvoir", "1947", "Intermediate", "Existentialism"),
(332, "The Second Sex", "Simone de Beauvoir", "1949", "Intermediate", "Existentialism"),
(333, "Man's Search for Meaning", "Viktor Frankl", "1946", "Advanced", "Existentialism"),
(334, "The Will to Meaning", "Viktor Frankl", "1969", "Advanced", "Existentialism"),
(335, "The Brothers Karamazov", "Fyodor Dostoevsky", "1880", "Advanced", "Existentialism"),
(336, "Crime and Punishment", "Fyodor Dostoevsky", "1866", "Advanced", "Existentialism"),
(337, "The Rebel", "Albert Camus", "1951", "Advanced", "Existentialism"),
(338, "The Book of Disquiet", "Fernando Pessoa", "1982", "Masterwork", "Existentialism"),
(339, "The Unbearable Lightness of Being", "Milan Kundera", "1984", "Masterwork", "Existentialism"),
(340, "The Courage to Be Disliked", "Ichiro Kishimi & Fumitake Koga", "2013", "Masterwork", "Existentialism"),

# 09. BUSINESS & ENTREPRENEURSHIP (55 books: 341-395)
(341, "The Personal MBA", "Josh Kaufman", "2010", "Foundation", "Business & Entrepreneurship"),
(342, "The Mom Test", "Rob Fitzpatrick", "2013", "Foundation", "Business & Entrepreneurship"),
(343, "The Lean Startup", "Eric Ries", "2011", "Foundation", "Business & Entrepreneurship"),
(344, "Zero to One", "Peter Thiel", "2014", "Foundation", "Business & Entrepreneurship"),
(345, "The Hard Thing About Hard Things", "Ben Horowitz", "2014", "Foundation", "Business & Entrepreneurship"),
(346, "High Output Management", "Andrew Grove", "1983", "Foundation", "Business & Entrepreneurship"),
(347, "The Founder's Dilemmas", "Noam Wasserman", "2012", "Foundation", "Business & Entrepreneurship"),
(348, "The Cold Start Problem", "Andrew Chen", "2021", "Foundation", "Business & Entrepreneurship"),
(349, "The Startup Owner's Manual", "Steve Blank & Bob Dorf", "2012", "Foundation", "Business & Entrepreneurship"),
(350, "The Four Steps to the Epiphany", "Steve Blank", "2003", "Foundation", "Business & Entrepreneurship"),
(351, "Disciplined Entrepreneurship", "Bill Aulet", "2013", "Foundation", "Business & Entrepreneurship"),
(352, "The E-Myth Revisited", "Michael Gerber", "1986", "Core", "Business & Entrepreneurship"),
(353, "Built to Sell", "John Warrillow", "2010", "Core", "Business & Entrepreneurship"),
(354, "Rework", "Jason Fried & David Heinemeier Hansson", "2010", "Core", "Business & Entrepreneurship"),
(355, "Company of One", "Paul Jarvis", "2019", "Core", "Business & Entrepreneurship"),
(356, "The $100 Startup", "Chris Guillebeau", "2012", "Core", "Business & Entrepreneurship"),
(357, "Shoe Dog", "Phil Knight", "2016", "Core", "Business & Entrepreneurship"),
(358, "The Everything Store", "Brad Stone", "2013", "Core", "Business & Entrepreneurship"),
(359, "Sam Walton: Made in America", "Sam Walton", "1992", "Core", "Business & Entrepreneurship"),
(360, "The Snowball", "Alice Schroeder", "2008", "Core", "Business & Entrepreneurship"),
(361, "The Outsiders", "William Thorndike", "2012", "Core", "Business & Entrepreneurship"),
(362, "Business Adventures", "John Brooks", "1969", "Core", "Business & Entrepreneurship"),
(363, "Barbarians at the Gate", "Bryan Burrough & John Helyar", "1989", "Core", "Business & Entrepreneurship"),
(364, "The Phoenix Project", "Gene Kim, Kevin Behr & George Spafford", "2013", "Core", "Business & Entrepreneurship"),
(365, "Measure What Matters", "John Doerr", "2017", "Intermediate", "Business & Entrepreneurship"),
(366, "Working Backwards", "Colin Bryar & Bill Carr", "2021", "Intermediate", "Business & Entrepreneurship"),
(367, "No Rules Rules", "Reed Hastings & Erin Meyer", "2020", "Intermediate", "Business & Entrepreneurship"),
(368, "Scaling Up", "Verne Harnish", "2014", "Intermediate", "Business & Entrepreneurship"),
(369, "Crossing the Chasm", "Geoffrey Moore", "1991", "Intermediate", "Business & Entrepreneurship"),
(370, "Traction", "Gino Wickman", "2007", "Intermediate", "Business & Entrepreneurship"),
(371, "Venture Deals", "Brad Feld & Jason Mendelson", "2011", "Intermediate", "Business & Entrepreneurship"),
(372, "Founders at Work", "Jessica Livingston", "2007", "Intermediate", "Business & Entrepreneurship"),
(373, "Founding Sales", "Pete Kazanjy", "2020", "Intermediate", "Business & Entrepreneurship"),
(374, "$100M Offers", "Alex Hormozi", "2021", "Intermediate", "Business & Entrepreneurship"),
(375, "$100M Leads", "Alex Hormozi", "2023", "Intermediate", "Business & Entrepreneurship"),
(376, "The Startup Way", "Eric Ries", "2017", "Intermediate", "Business & Entrepreneurship"),
(377, "The Great CEO Within", "Matt Mochary", "2018", "Intermediate", "Business & Entrepreneurship"),
(378, "The Four", "Scott Galloway", "2017", "Intermediate", "Business & Entrepreneurship"),
(379, "The Power Law", "Sebastian Mallaby", "2022", "Advanced", "Business & Entrepreneurship"),
(380, "The Art of the Start", "Guy Kawasaki", "2004", "Advanced", "Business & Entrepreneurship"),
(381, "The Art of the Start 2.0", "Guy Kawasaki", "2015", "Advanced", "Business & Entrepreneurship"),
(382, "The Startup Playbook", "David Kidder", "2012", "Advanced", "Business & Entrepreneurship"),
(383, "The 4-Hour Workweek", "Tim Ferriss", "2007", "Advanced", "Business & Entrepreneurship"),
(384, "The Pumpkin Plan", "Mike Michalowicz", "2012", "Advanced", "Business & Entrepreneurship"),
(385, "Profit First", "Mike Michalowicz", "2014", "Advanced", "Business & Entrepreneurship"),
(386, "Clockwork", "Mike Michalowicz", "2018", "Advanced", "Business & Entrepreneurship"),
(387, "The Toilet Paper Entrepreneur", "Mike Michalowicz", "2008", "Advanced", "Business & Entrepreneurship"),
(388, "The Innovator's DNA", "Dyer, Gregersen & Christensen", "2011", "Advanced", "Business & Entrepreneurship"),
(389, "The Founder's Mentality", "Zook & Allen", "2016", "Masterwork", "Business & Entrepreneurship"),
(390, "Scaling Up Excellence", "Sutton & Rao", "2014", "Masterwork", "Business & Entrepreneurship"),
(391, "The Messy Middle", "Scott Belsky", "2018", "Masterwork", "Business & Entrepreneurship"),
(392, "Angel", "Jason Calacanis", "2017", "Masterwork", "Business & Entrepreneurship"),
(393, "The Business of Venture Capital", "Mahendra Ramsinghani", "2014", "Masterwork", "Business & Entrepreneurship"),
(394, "The Art of Profitability", "Adrian Slywotzky", "2002", "Masterwork", "Business & Entrepreneurship"),
(395, "The Business of the 21st Century", "Robert Kiyosaki", "2010", "Masterwork", "Business & Entrepreneurship"),

# 10. MANAGEMENT & LEADERSHIP (50 books: 396-445)
(396, "The Practice of Management", "Peter Drucker", "1954", "Foundation", "Management & Leadership"),
(397, "Management: Tasks, Responsibilities, Practices", "Peter Drucker", "1973", "Foundation", "Management & Leadership"),
(398, "First, Break All the Rules", "Marcus Buckingham & Curt Coffman", "1999", "Foundation", "Management & Leadership"),
(399, "The Fearless Organization", "Amy Edmondson", "2018", "Foundation", "Management & Leadership"),
(400, "The Five Dysfunctions of a Team", "Patrick Lencioni", "2002", "Foundation", "Management & Leadership"),
(401, "Multipliers", "Liz Wiseman", "2010", "Foundation", "Management & Leadership"),
(402, "Turn the Ship Around!", "L. David Marquet", "2012", "Foundation", "Management & Leadership"),
(403, "Team of Teams", "Stanley McChrystal et al.", "2015", "Foundation", "Management & Leadership"),
(404, "Organizations", "James March & Herbert Simon", "1958", "Foundation", "Management & Leadership"),
(405, "Images of Organization", "Gareth Morgan", "1986", "Foundation", "Management & Leadership"),
(406, "The Leadership Challenge", "James Kouzes & Barry Posner", "1987", "Core", "Management & Leadership"),
(407, "Good to Great", "Jim Collins", "2001", "Core", "Management & Leadership"),
(408, "Built to Last", "Jim Collins & Jerry Porras", "1994", "Core", "Management & Leadership"),
(409, "The Score Takes Care of Itself", "Bill Walsh", "2009", "Core", "Management & Leadership"),
(410, "The Practice of Adaptive Leadership", "Ronald Heifetz et al.", "2009", "Core", "Management & Leadership"),
(411, "Power: Why Some People Have It", "Jeffrey Pfeffer", "2010", "Core", "Management & Leadership"),
(412, "What Got You Here Won't Get You There", "Marshall Goldsmith", "2007", "Core", "Management & Leadership"),
(413, "Leaders Eat Last", "Simon Sinek", "2014", "Core", "Management & Leadership"),
(414, "Start with Why", "Simon Sinek", "2009", "Core", "Management & Leadership"),
(415, "The Infinite Game", "Simon Sinek", "2019", "Core", "Management & Leadership"),
(416, "Extreme Ownership", "Jocko Willink & Leif Babin", "2015", "Core", "Management & Leadership"),
(417, "The One Minute Manager", "Ken Blanchard & Spencer Johnson", "1982", "Core", "Management & Leadership"),
(418, "Toyota Production System", "Taiichi Ohno", "1988", "Intermediate", "Management & Leadership"),
(419, "The Machine That Changed the World", "Womack, Jones & Roos", "1990", "Intermediate", "Management & Leadership"),
(420, "Leadership Pipeline", "Ram Charan et al.", "2000", "Intermediate", "Management & Leadership"),
(421, "The Knowing-Doing Gap", "Jeffrey Pfeffer & Robert Sutton", "2000", "Intermediate", "Management & Leadership"),
(422, "The Leadership Moment", "Michael Useem", "1998", "Intermediate", "Management & Leadership"),
(423, "Leadership in Turbulent Times", "Doris Kearns Goodwin", "2018", "Intermediate", "Management & Leadership"),
(424, "The Captain Class", "Sam Walker", "2017", "Intermediate", "Management & Leadership"),
(425, "The Ride of a Lifetime", "Robert Iger", "2019", "Intermediate", "Management & Leadership"),
(426, "The Coaching Habit", "Michael Bungay Stanier", "2016", "Intermediate", "Management & Leadership"),
(427, "The 21 Irrefutable Laws of Leadership", "John Maxwell", "1998", "Intermediate", "Management & Leadership"),
(428, "The Five Levels of Leadership", "John Maxwell", "2007", "Intermediate", "Management & Leadership"),
(429, "Leaders", "Stanley McChrystal", "2015", "Intermediate", "Management & Leadership"),
(430, "The Leadership Pipeline", "Charan et al.", "2000", "Intermediate", "Management & Leadership"),
(431, "The Advantage", "Patrick Lencioni", "2012", "Advanced", "Management & Leadership"),
(432, "The Motive", "Patrick Lencioni", "2020", "Advanced", "Management & Leadership"),
(433, "The Truth About Employee Engagement", "Patrick Lencioni", "2015", "Advanced", "Management & Leadership"),
(434, "The Ideal Team Player", "Patrick Lencioni", "2016", "Advanced", "Management & Leadership"),
(435, "The Four Obsessions of an Extraordinary Executive", "Lencioni", "2000", "Advanced", "Management & Leadership"),
(436, "The Dichotomy of Leadership", "Willink & Babin", "2018", "Advanced", "Management & Leadership"),
(437, "Leadership Strategy and Tactics", "Jocko Willink", "2020", "Advanced", "Management & Leadership"),
(438, "The Servant Leader", "James Hunter", "1998", "Advanced", "Management & Leadership"),
(439, "Servant Leadership", "Robert Greenleaf", "1977", "Advanced", "Management & Leadership"),
(440, "Leadership Without Easy Answers", "Ronald Heifetz", "1994", "Masterwork", "Management & Leadership"),
(441, "The Work of Leaders", "Strack et al.", "2011", "Masterwork", "Management & Leadership"),
(442, "The Servant Leadership Handbook", "Kent Keith", "2011", "Masterwork", "Management & Leadership"),
(443, "The Leader's Guide to Storytelling", "Stephen Denning", "2011", "Masterwork", "Management & Leadership"),
(444, "The Leadership Dojo", "Richard Strozzi-Heckler", "2007", "Masterwork", "Management & Leadership"),
(445, "The Leadership Engine", "Noel Tichy", "1997", "Masterwork", "Management & Leadership"),

# 11. STRATEGY (45 books: 446-490)
(446, "Good Strategy/Bad Strategy", "Richard Rumelt", "2011", "Foundation", "Strategy"),
(447, "Competitive Strategy", "Michael Porter", "1980", "Foundation", "Strategy"),
(448, "Competitive Advantage", "Michael Porter", "1985", "Foundation", "Strategy"),
(449, "Playing to Win", "A. G. Lafley & Roger Martin", "2013", "Foundation", "Strategy"),
(450, "The Strategy of Conflict", "Thomas Schelling", "1960", "Foundation", "Strategy"),
(451, "The Art of Strategy", "Avinash Dixit & Barry Nalebuff", "2008", "Foundation", "Strategy"),
(452, "Thinking Strategically", "Avinash Dixit & Barry Nalebuff", "1991", "Foundation", "Strategy"),
(453, "Games of Strategy", "Dixit, Skeath & Reiley", "2009", "Foundation", "Strategy"),
(454, "Theory of Games and Economic Behavior", "von Neumann & Morgenstern", "1944", "Foundation", "Strategy"),
(455, "The Evolution of Cooperation", "Robert Axelrod", "1984", "Core", "Strategy"),
(456, "The Art of War", "Sun Tzu", "-500", "Core", "Strategy"),
(457, "On War", "Carl von Clausewitz", "1832", "Core", "Strategy"),
(458, "The Prince", "Niccolò Machiavelli", "1532", "Core", "Strategy"),
(459, "Strategy: A History", "Lawrence Freedman", "2013", "Core", "Strategy"),
(460, "The Tragedy of Great Power Politics", "John Mearsheimer", "2001", "Core", "Strategy"),
(461, "Diplomacy", "Henry Kissinger", "1994", "Core", "Strategy"),
(462, "The Grand Chessboard", "Zbigniew Brzezinski", "1997", "Core", "Strategy"),
(463, "The Rise and Fall of the Great Powers", "Paul Kennedy", "1987", "Core", "Strategy"),
(464, "The Twenty Years' Crisis", "E. H. Carr", "1939", "Core", "Strategy"),
(465, "The Logic of Collective Action", "Mancur Olson", "1965", "Core", "Strategy"),
(466, "Seeing Like a State", "James C. Scott", "1998", "Intermediate", "Strategy"),
(467, "The Innovator's Dilemma", "Clayton Christensen", "1997", "Intermediate", "Strategy"),
(468, "7 Powers", "Hamilton Helmer", "2016", "Intermediate", "Strategy"),
(469, "The Goal", "Eliyahu Goldratt", "1984", "Intermediate", "Strategy"),
(470, "Only the Paranoid Survive", "Andrew Grove", "1996", "Intermediate", "Strategy"),
(471, "Blitzscaling", "Reid Hoffman & Chris Yeh", "2018", "Intermediate", "Strategy"),
(472, "The Sovereign Individual", "James Dale Davidson & William Rees-Mogg", "1997", "Intermediate", "Strategy"),
(473, "The Changing World Order", "Ray Dalio", "2021", "Intermediate", "Strategy"),
(474, "Strategy Beyond Markets", "Pankaj Ghemawat", "2011", "Intermediate", "Strategy"),
(475, "Red Team", "Micah Zenko", "2015", "Intermediate", "Strategy"),
(476, "The Art of Action", "Stephen Bungay", "2011", "Intermediate", "Strategy"),
(477, "The Mind of the Strategist", "Kenichi Ohmae", "1982", "Advanced", "Strategy"),
(478, "The Strategy Paradox", "Michael Raynor", "2007", "Advanced", "Strategy"),
(479, "The Innovator's Solution", "Clayton Christensen & Michael Raynor", "2003", "Advanced", "Strategy"),
(480, "The Art of War in Business", "Sun Tzu", "1990", "Advanced", "Strategy"),
(481, "The Strategist", "Cynthia Montgomery", "2012", "Advanced", "Strategy"),
(482, "Your Strategy Needs a Strategy", "Reeves et al.", "2015", "Advanced", "Strategy"),
(483, "The Strategy Book", "Max McKeown", "2012", "Advanced", "Strategy"),
(484, "Blue Ocean Strategy", "Kim & Mauborgne", "2005", "Advanced", "Strategy"),
(485, "The Halo Effect", "Phil Rosenzweig", "2007", "Masterwork", "Strategy"),
(486, "The Rise and Fall of Strategic Planning", "Henry Mintzberg", "1994", "Masterwork", "Strategy"),
(487, "The Lords of Strategy", "Walter Kiechel", "2010", "Masterwork", "Strategy"),
(488, "Co-opetition", "Brandenburger & Nalebuff", "1996", "Masterwork", "Strategy"),
(489, "The Grand Strategy of the Roman Empire", "Edward Luttwak", "1976", "Masterwork", "Strategy"),
(490, "The Grand Strategy of the Byzantine Empire", "Edward Luttwak", "2009", "Masterwork", "Strategy"),

# 12. MARKETING & SALES (30 books: 491-520)
(491, "Marketing Management", "Philip Kotler & Kevin Keller", "2016", "Foundation", "Marketing & Sales"),
(492, "Obviously Awesome", "April Dunford", "2019", "Foundation", "Marketing & Sales"),
(493, "This Is Marketing", "Seth Godin", "2018", "Foundation", "Marketing & Sales"),
(494, "Positioning", "Al Ries & Jack Trout", "1980", "Foundation", "Marketing & Sales"),
(495, "The 22 Immutable Laws of Marketing", "Al Ries & Jack Trout", "1993", "Foundation", "Marketing & Sales"),
(496, "How Brands Grow", "Byron Sharp", "2010", "Foundation", "Marketing & Sales"),
(497, "The Brand Gap", "Marty Neumeier", "2003", "Core", "Marketing & Sales"),
(498, "Ogilvy on Advertising", "David Ogilvy", "1983", "Core", "Marketing & Sales"),
(499, "Scientific Advertising", "Claude Hopkins", "1923", "Core", "Marketing & Sales"),
(500, "The Boron Letters", "Gary Halbert", "1998", "Core", "Marketing & Sales"),
(501, "Hey, Whipple, Squeeze This", "Luke Sullivan", "1998", "Core", "Marketing & Sales"),
(502, "Alchemy", "Rory Sutherland", "2019", "Core", "Marketing & Sales"),
(503, "New Sales. Simplified.", "Mike Weinberg", "2012", "Core", "Marketing & Sales"),
(504, "Fanatical Prospecting", "Jeb Blount", "2015", "Intermediate", "Marketing & Sales"),
(505, "The Qualified Sales Leader", "John McMahon", "2006", "Intermediate", "Marketing & Sales"),
(506, "Hacking Growth", "Sean Ellis & Morgan Brown", "2017", "Intermediate", "Marketing & Sales"),
(507, "Platform Revolution", "Geoffrey Parker et al.", "2016", "Intermediate", "Marketing & Sales"),
(508, "Cashvertising", "Drew Eric Whitman", "2008", "Intermediate", "Marketing & Sales"),
(509, "Breakthrough Advertising", "Eugene Schwartz", "1966", "Intermediate", "Marketing & Sales"),
(510, "The 1-Page Marketing Plan", "Allan Dib", "2016", "Intermediate", "Marketing & Sales"),
(511, "Building a StoryBrand", "Donald Miller", "2017", "Intermediate", "Marketing & Sales"),
(512, "Marketing Made Simple", "Miller & Papasan", "2020", "Advanced", "Marketing & Sales"),
(513, "Purple Cow", "Seth Godin", "2003", "Advanced", "Marketing & Sales"),
(514, "Permission Marketing", "Seth Godin", "1999", "Advanced", "Marketing & Sales"),
(515, "Tribes", "Seth Godin", "2008", "Advanced", "Marketing & Sales"),
(516, "All Marketers Tell Stories", "Seth Godin", "2005", "Advanced", "Marketing & Sales"),
(517, "The Copywriter's Handbook", "Robert Bly", "1985", "Masterwork", "Marketing & Sales"),
(518, "Tested Advertising Methods", "John Caples", "1932", "Masterwork", "Marketing & Sales"),
(519, "Confessions of an Advertising Man", "David Ogilvy", "1963", "Masterwork", "Marketing & Sales"),
(520, "The Ultimate Sales Machine", "Chet Holmes", "2007", "Masterwork", "Marketing & Sales")
]

print(f"Loaded {len(RAW_DATA)} books in part 2")
